(function(root){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const base={head:[0,-116],neck:[0,-94],hip:[0,-43],le:[-25,-70],lh:[-31,-47],re:[25,-70],rh:[31,-47],lk:[-16,-22],lf:[-19,0],rk:[16,-22],rf:[19,0]};
const actions=['Idle','Walk','Run','Jump','Wave','Dance','Punch','Kick','Sit','Fall','Celebrate','Custom pose'];
const links=[['neck','hip'],['neck','le'],['le','lh'],['neck','re'],['re','rh'],['hip','lk'],['lk','lf'],['hip','rk'],['rk','rf']];
function pose(action,u,seconds=0,clip={}){let p=clone(base),w=Math.sin(seconds*Math.PI*2*1.5),bounce=0; const set=(k,x,y)=>p[k]=[x,y];
if(action==='Custom pose'){let a=clip.poseA||base,b=clip.poseB||base;Object.keys(base).forEach(k=>p[k]=[a[k][0]+(b[k][0]-a[k][0])*u,a[k][1]+(b[k][1]-a[k][1])*u]);return p;}
if(action==='Idle')bounce=Math.sin(seconds*2)*1.5;
if(action==='Walk'||action==='Run'){let fast=action==='Run',s=fast?36:23;w=Math.sin(seconds*Math.PI*2*(fast?2.4:1.3));set('lk',w*s-5,-23);set('lf',w*s*1.35-7,-Math.max(0,-w)*(fast?18:10));set('rk',-w*s+5,-23);set('rf',-w*s*1.35+7,-Math.max(0,w)*(fast?18:10));set('le',-w*24-10,-72);set('lh',-w*(fast?40:28)-12,fast?-77:-49);set('re',w*24+10,-72);set('rh',w*(fast?40:28)+12,fast?-77:-49);bounce=-Math.abs(w)*(fast?9:3);if(fast){p.neck[0]=10;p.head[0]=13;}}
if(action==='Jump'){let j=Math.sin(Math.PI*u);bounce=-j*83;set('le',-29,-80-j*23);set('lh',-37,-58-j*78);set('re',29,-80-j*23);set('rh',37,-58-j*78);set('lk',-22,-20-j*5);set('lf',-31,-j*14);set('rk',22,-20-j*5);set('rf',31,-j*14);}
if(action==='Wave'){set('re',29,-106);set('rh',36+Math.sin(seconds*10)*13,-144);bounce=Math.sin(seconds*3)*1.5;}
if(action==='Dance'){w=Math.sin(seconds*6);p.hip[0]=w*10;p.neck[0]=-w*9;p.head[0]=-w*13;set('le',-35,-85+w*18);set('lh',-51,-105+w*25);set('re',35,-85-w*18);set('rh',51,-105-w*25);set('lk',-24,-20);set('rk',24,-20);set('lf',-32,-Math.max(0,w)*13);set('rf',32,-Math.max(0,-w)*13);bounce=-Math.abs(w)*5;}
if(action==='Punch'){let q=Math.pow(Math.max(0,Math.sin(u*Math.PI)),3);set('re',25+q*18,-89);set('rh',16+q*65,-95);set('le',-17,-76);set('lh',5,-88);p.neck[0]=q*12;p.head[0]=q*16;set('lf',-27,0);set('rf',30,0);}
if(action==='Kick'){let q=Math.sin(Math.PI*u);set('rk',20+q*23,-22-q*33);set('rf',19+q*62,-q*58);set('le',-30,-80);set('lh',-40,-97);p.neck[0]=-q*12;p.head[0]=-q*16;}
if(action==='Sit'){set('hip',0,-24);set('lk',28,-24);set('lf',28,0);set('rk',33,-23);set('rf',35,0);set('neck',0,-74);set('head',0,-96);set('le',17,-49);set('lh',30,-27);set('re',20,-50);set('rh',35,-26);}
if(action==='Fall'){let a=u*Math.PI/2;Object.keys(p).forEach(k=>{let [x,y]=p[k];p[k]=[x*Math.cos(a)-y*Math.sin(a),x*Math.sin(a)+y*Math.cos(a)];});}
if(action==='Celebrate'){set('le',-31,-110);set('lh',-45,-143);set('re',31,-110);set('rh',45,-143);bounce=-Math.abs(Math.sin(seconds*5))*18;}
Object.values(p).forEach(v=>v[1]+=bounce);return p;}
function duration(project){return Math.max(1,...project.actors.map(a=>a.clips.reduce((s,c)=>s+c.duration,0)),...project.captions.map(c=>c.start+c.duration),...project.props.map(p=>p.start+p.duration));}
function clipAt(actor,t){let start=0;for(let i=0;i<actor.clips.length;i++){let c=actor.clips[i];if(t<start+c.duration||i===actor.clips.length-1){let u=Math.max(0,Math.min(1,(t-start)/c.duration));return {clip:c,index:i,start,u,seconds:Math.max(0,Math.min(c.duration,t-start))};}start+=c.duration;}return null;}
function ease(u,type){return type==='linear'?u:u*u*(3-2*u);}
function actorState(actor,t){let at=clipAt(actor,t);if(!at)return{x:actor.x,y:actor.y,pose:pose('Idle',0,t),scale:actor.scale,flip:actor.flip};let c=at.clip,u=ease(at.u,c.easing);return{x:c.fromX+(c.toX-c.fromX)*u,y:c.fromY+(c.toY-c.fromY)*u,pose:pose(c.action,u,at.seconds,c),scale:actor.scale,flip:c.flip??actor.flip,at};}
function sizes(aspect,m=1){return aspect==='tall'?[540*m,960*m]:aspect==='square'?[720*m,720*m]:[960*m,540*m];}
function transform(project,W,H){const unit=Math.min(W/960,H/540)*project.zoom/100;return{unit,point(x,y){return[W/2+(x/100-.5)*W*project.zoom/100,H*.77+(y/100-.77)*H*project.zoom/100];},inverse(x,y){return[50+(x-W/2)/W*100/(project.zoom/100),77+(y-H*.77)/H*100/(project.zoom/100)];}};}
function render(ctx,project,t,options={}){let W=ctx.canvas.width,H=ctx.canvas.height,tr=transform(project,W,H),night=project.background==='night',colors={paper:'#f3f1eb',sky:'#dfeef6',night:'#191e34',white:'#ffffff',green:'#00b140'};ctx.fillStyle=colors[project.background]||colors.paper;ctx.fillRect(0,0,W,H);if(project.ground){let y=tr.point(0,77)[1];ctx.fillStyle=night?'#222942':project.background==='green'?'#00b140':project.background==='sky'?'#c5d8cb':'#e9e6df';ctx.fillRect(0,y+2,W,H-y);ctx.strokeStyle=night?'#3b4568':'#cfcec8';ctx.lineWidth=1.3*tr.unit;ctx.beginPath();ctx.moveTo(0,y+2);ctx.lineTo(W,y+2);ctx.stroke();}
const geometries=[];
project.props.forEach(p=>{let u=ease(Math.max(0,Math.min(1,(t-p.start)/p.duration)),'smooth');let [x,y]=tr.point(p.x+(p.toX-p.x)*u,p.y+(p.toY-p.y)*u),s=p.size*tr.unit;ctx.save();ctx.translate(x,y);ctx.strokeStyle=p.color;ctx.fillStyle=p.color;ctx.lineWidth=5*tr.unit;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();if(p.type==='ball'){ctx.arc(0,-s/2,s/2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffffff80';ctx.lineWidth=2*tr.unit;ctx.beginPath();ctx.arc(-s/10,-s*.55,s*.3,Math.PI,Math.PI*1.55);ctx.stroke();}else if(p.type==='box'){ctx.fillRect(-s/2,-s,s,s);ctx.strokeStyle='#ffffff60';ctx.lineWidth=2*tr.unit;ctx.strokeRect(-s/2+5,-s+5,s-10,s-10);}else if(p.type==='chair'){ctx.moveTo(-s/2,0);ctx.lineTo(-s/2,-s*1.4);ctx.moveTo(-s/2,-s*.55);ctx.lineTo(s/2,-s*.55);ctx.lineTo(s/2,0);ctx.stroke();}else{for(let j=0;j<10;j++){let a=-Math.PI/2+j*Math.PI/5,r=j%2?s*.23:s*.52;ctx.lineTo(Math.cos(a)*r,-s*.5+Math.sin(a)*r);}ctx.closePath();ctx.fill();}ctx.restore();geometries.push({kind:'prop',id:p.id,x,y,s});if(options.selectedProp===p.id){ctx.strokeStyle='#9673ed';ctx.lineWidth=2;ctx.setLineDash([4,4]);ctx.strokeRect(x-s*.7,y-s*1.5,s*1.4,s*1.7);ctx.setLineDash([]);}});
project.actors.forEach(actor=>{let st=actorState(actor,t);if(options.poseEdit&&options.actorId===actor.id){let c=actor.clips.find(c=>c.id===options.clipId);if(c){st.pose=clone(options.poseEdit==='a'?c.poseA:c.poseB);st.x=options.poseEdit==='a'?c.fromX:c.toX;st.y=options.poseEdit==='a'?c.fromY:c.toY;st.flip=c.flip;}}
let [x,y]=tr.point(st.x,st.y),s=tr.unit*actor.scale,flip=st.flip?-1:1;ctx.save();ctx.translate(x,y);ctx.scale(s*flip,s);ctx.strokeStyle=actor.color;ctx.lineWidth=6;ctx.lineCap='round';ctx.lineJoin='round';links.forEach(([a,b])=>{ctx.beginPath();ctx.moveTo(...st.pose[a]);ctx.lineTo(...st.pose[b]);ctx.stroke();});let h=st.pose.head,n=st.pose.neck;ctx.beginPath();ctx.moveTo(...h);ctx.lineTo(...n);ctx.stroke();ctx.beginPath();ctx.arc(h[0],h[1],18,0,Math.PI*2);ctx.fillStyle=colors[project.background]||colors.paper;ctx.fill();ctx.stroke();ctx.fillStyle=actor.color;ctx.beginPath();ctx.arc(h[0]+6,h[1]-2,2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(h[0]+3,h[1]+3,6,0,.65*Math.PI);ctx.lineWidth=2;ctx.stroke();ctx.restore();
let joints={};Object.entries(st.pose).forEach(([k,[jx,jy]])=>joints[k]=[x+jx*s*flip,y+jy*s]);geometries.push({kind:'actor',id:actor.id,x,y,s,flip,joints});if(options.actorId===actor.id){ctx.strokeStyle='#9b7ed9';ctx.lineWidth=1.5;ctx.setLineDash([4,4]);ctx.beginPath();ctx.ellipse(x,y+10*tr.unit,32*s,7*tr.unit,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);if(options.poseEdit){Object.entries(joints).forEach(([k,[jx,jy]])=>{ctx.fillStyle=k==='head'?'#d7f47b':'#9875ed';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(jx,jy,6*tr.unit,0,Math.PI*2);ctx.fill();ctx.stroke();});}}});
project.captions.filter(c=>t>=c.start&&t<c.start+c.duration).forEach(c=>{let fontSize=24*Math.min(W/960,H/540),max=W*.8;ctx.font='600 '+fontSize+'px system-ui';let words=c.text.split(/\s+/),lines=[''];for(const word of words){let last=lines.length-1;if(ctx.measureText(lines[last]+' '+word).width>max&&lines[last])lines.push(word);else lines[last]+=(lines[last]?' ':'')+word;}lines=lines.slice(0,5);let lh=fontSize*1.4,bw=Math.min(W*.92,Math.max(120,...lines.map(l=>ctx.measureText(l).width))+40),bh=lines.length*lh+20,cy=H*c.y/100;ctx.fillStyle=night?'#f3f1ebe8':'#20232be8';ctx.beginPath();ctx.roundRect((W-bw)/2,cy-bh/2,bw,bh,10);ctx.fill();ctx.fillStyle=night?'#20232b':'#fff';ctx.textAlign='center';ctx.textBaseline='middle';lines.forEach((line,i)=>ctx.fillText(line,W/2,cy+(i-(lines.length-1)/2)*lh,W*.86));});return geometries;}
const api={base,actions,pose,duration,clipAt,actorState,ease,sizes,transform,render,clone};root.StickEngine=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
