'use strict';
const E=StickEngine,$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=>crypto.randomUUID(),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),colours=['#6c55b5','#dd714e','#238e91','#395ec0','#b4477e','#495365'];
function makeClip(action,x=35,y=77,flip=false){return{id:uid(),action,duration:action==='Jump'?1.2:2,fromX:x,toX:clamp(x+(action==='Walk'?15:action==='Run'?25:0)*(flip?-1:1),0,100),fromY:y,toY:y,flip,easing:'smooth',poseA:E.clone(E.base),poseB:E.clone(E.base)};}
function makeActor(name,color,x){return{id:uid(),name,color,x,y:77,scale:1.25,flip:false,clips:[]};}
function demo(){let a=makeActor('Violet',colours[0],24),b=makeActor('Amber',colours[1],72);b.flip=true;let c=makeClip('Walk',24);c.duration=3;c.toX=43;let d=makeClip('Wave',43);d.duration=3;a.clips=[c,d];let f=makeClip('Idle',72,77,true);f.duration=3;let g=makeClip('Celebrate',72,77,true);g.duration=3;b.clips=[f,g];return{version:1,title:'A little hello',aspect:'wide',background:'paper',zoom:100,ground:true,actors:[a,b],props:[],captions:[{id:uid(),text:'Every story starts with a little hello.',start:0,duration:3,y:19},{id:uid(),text:'What happens next? You decide.',start:3,duration:3,y:19}]};}
function validate(p){const finite=(n,a,b)=>typeof n==='number'&&Number.isFinite(n)&&n>=a&&n<=b,txt=(s,n)=>typeof s==='string'&&s.length<=n,color=s=>/^#[0-9a-f]{6}$/i.test(s),id=s=>typeof s==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(s),point=v=>Array.isArray(v)&&v.length===2&&v.every(n=>finite(n,-400,400));if(!p||p.version!==1||!txt(p.title,60)||!['wide','tall','square'].includes(p.aspect)||!['paper','sky','night','white','green'].includes(p.background)||!finite(p.zoom,60,160)||typeof p.ground!=='boolean'||!Array.isArray(p.actors)||p.actors.length>20||!Array.isArray(p.props)||p.props.length>100||!Array.isArray(p.captions)||p.captions.length>100)throw Error('This is not a valid Stickmotion project.');const ids=new Set();function checkId(v){if(!id(v)||ids.has(v))throw Error('Invalid or duplicate object ID.');ids.add(v);}p.actors.forEach(a=>{checkId(a.id);if(!txt(a.name,30)||!color(a.color)||!finite(a.x,0,100)||!finite(a.y,0,100)||!finite(a.scale,.4,3)||typeof a.flip!=='boolean'||!Array.isArray(a.clips)||a.clips.length>200)throw Error('Invalid character.');a.clips.forEach(c=>{checkId(c.id);if(!E.actions.includes(c.action)||!finite(c.duration,.2,30)||!['fromX','fromY','toX','toY'].every(k=>finite(c[k],0,100))||typeof c.flip!=='boolean'||!['smooth','linear'].includes(c.easing)||![c.poseA,c.poseB].every(pose=>pose&&Object.keys(E.base).every(k=>point(pose[k]))))throw Error('Invalid action clip.');});});p.props.forEach(o=>{checkId(o.id);if(!['ball','box','chair','star'].includes(o.type)||!color(o.color)||!['x','y','toX','toY'].every(k=>finite(o[k],0,100))||!finite(o.size,10,200)||!finite(o.start,0,600)||!finite(o.duration,.2,30))throw Error('Invalid prop.');});p.captions.forEach(c=>{checkId(c.id);if(!txt(c.text,240)||!finite(c.start,0,600)||!finite(c.duration,.2,30)||!finite(c.y,5,95))throw Error('Invalid caption.');});if(E.duration(p)>600)throw Error('Projects can be up to 10 minutes long.');return p;}
let project=demo(),stored=false;try{let raw=localStorage.getItem('stickmotion-v1');if(raw){project=validate(JSON.parse(raw));stored=true;}}catch{}
let actorId=project.actors[0]?.id,clipId=project.actors[0]?.clips[0]?.id,propId=null,captionId=null,poseEdit=null,time=0,playing=false,loop=true,speed=1,last=0,geometry=[],history=[],future=[],drag=null,recording=null,toastTimer;
const canvas=$('stage'),ctx=canvas.getContext('2d');
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
function save(){try{localStorage.setItem('stickmotion-v1',JSON.stringify(project));$('saveStatus').textContent='Saved on this device';}catch{$('saveStatus').textContent='Save a project file to keep your work';}}
function checkpoint(){history.push(E.clone(project));if(history.length>60)history.shift();future=[];}
function selectedActor(){return project.actors.find(a=>a.id===actorId);}
function selectedClip(){return selectedActor()?.clips.find(c=>c.id===clipId);}
function finish(){save();refresh();}
function mutate(fn){if(recording)return;checkpoint();try{fn();validate(project);}catch(err){project=history.pop();toast(err.message||'This change could not be applied.');}finish();}
function saneSelection(){if(!selectedActor()){actorId=project.actors[0]?.id;clipId=selectedActor()?.clips[0]?.id;}if(!selectedClip()){clipId=null;poseEdit=null;}if(!project.props.some(p=>p.id===propId))propId=null;if(!project.captions.some(c=>c.id===captionId))captionId=null;}
function stop(){playing=false;$('playBtn').textContent='▶';$('playBtn').setAttribute('aria-label','Play animation');}
function selectActor(id){stop();actorId=id;clipId=null;propId=captionId=poseEdit=null;refresh();}
function selectClip(aid,cid){stop();actorId=aid;clipId=cid;propId=captionId=poseEdit=null;let a=selectedActor(),i=a.clips.findIndex(c=>c.id===cid);time=a.clips.slice(0,i).reduce((s,c)=>s+c.duration,0);refresh();}
function addAction(action){if(!E.actions.includes(action))throw Error('Unknown action');if(recording)return;if(!selectedActor()){if(!addActor())return;}let a=selectedActor();if(a.clips.length>=200||E.duration(project)>570){toast('This project has reached its clip or duration limit.');return;}mutate(()=>{let prev=a.clips.at(-1),c=makeClip(action,prev?.toX??a.x,prev?.toY??a.y,prev?.flip??a.flip);if(action==='Custom pose'&&prev){c.poseA=E.pose(prev.action,1,prev.duration,prev);c.poseB=E.clone(c.poseA);}time=a.clips.reduce((s,c)=>s+c.duration,0);a.clips.push(c);clipId=c.id;propId=captionId=null;poseEdit=action==='Custom pose'?'a':null;stop();});return clipId;}
function addActor(){if(project.actors.length>=20){toast('Up to 20 characters per project.');return false;}mutate(()=>{let n=project.actors.length,a=makeActor('Character '+(n+1),colours[n%colours.length],30+(n%5)*10);project.actors.push(a);actorId=a.id;clipId=propId=captionId=poseEdit=null;});return actorId;}
function draw(){geometry=E.render(ctx,project,time,playing||recording?{}:{actorId:propId||captionId?null:actorId,clipId,poseEdit,selectedProp:propId});updateTime();}
function updateTime(){let d=E.duration(project);$('timeNow').textContent=time.toFixed(2);$('timeTotal').textContent=d.toFixed(2);$('scrubber').max=d;$('scrubber').value=time;document.querySelectorAll('.playhead').forEach(e=>e.style.left=clamp(time/d*100,0,100)+'%');}
function refresh(){saneSelection();time=clamp(time,0,E.duration(project));let [w,h]=E.sizes(project.aspect);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}canvas.style.aspectRatio=w+'/'+h;$('title').value=project.title;$('sceneName').textContent=project.title||'Untitled animation';$('background').value=project.background;$('aspect').value=project.aspect;$('zoom').value=project.zoom;$('zoomValue').textContent=project.zoom+'%';$('ground').checked=project.ground;$('castCount').textContent=project.actors.length+' actors';$('undoBtn').disabled=!history.length;$('redoBtn').disabled=!future.length;
$('actors').innerHTML=project.actors.map(a=>'<button class="actor '+(a.id===actorId?'selected':'')+'" data-actor="'+a.id+'"><span class="actor-dot" style="background:'+a.color+'"></span>'+esc(a.name)+'<small>'+a.clips.length+' clips</small></button>').join('');$('actors').querySelectorAll('[data-actor]').forEach(b=>b.onclick=()=>selectActor(b.dataset.actor));$('selectionStatus').textContent=project.actors.length+' characters · '+project.actors.reduce((s,a)=>s+a.clips.length,0)+' clips';renderTracks();renderSettings();$('stageHint').textContent=poseEdit?'Drag the coloured joints to edit the '+(poseEdit==='a'?'start':'end')+' pose · Preview to see the transition':'Drag a character or prop to position it · Select a clip to edit movement';draw();}
function renderTracks(){let d=E.duration(project),html='';project.actors.forEach(a=>{let start=0;html+='<div class="track"><span class="track-name">'+esc(a.name)+'</span><div class="track-clips">';a.clips.forEach(c=>{html+='<button title="'+esc(c.action)+' · '+c.duration+' seconds" class="timeline-clip '+(c.id===clipId?'selected':'')+'" data-a="'+a.id+'" data-c="'+c.id+'" style="left:'+start/d*100+'%;width:'+c.duration/d*100+'%">'+esc(c.action)+'<span>'+c.duration+'s</span></button>';start+=c.duration;});html+='<i class="playhead"></i></div></div>';});project.captions.forEach(c=>{html+='<div class="track caption-track"><span class="track-name">Caption</span><div class="track-clips"><button class="timeline-clip '+(c.id===captionId?'selected':'')+'" data-caption="'+c.id+'" style="left:'+c.start/d*100+'%;width:'+c.duration/d*100+'%">'+esc(c.text)+'</button><i class="playhead"></i></div></div>';});project.props.forEach(p=>{html+='<div class="track caption-track"><span class="track-name">'+esc(p.type)+'</span><div class="track-clips"><button class="timeline-clip '+(p.id===propId?'selected':'')+'" data-propid="'+p.id+'" style="left:'+p.start/d*100+'%;width:'+p.duration/d*100+'%">Move '+esc(p.type)+'</button><i class="playhead"></i></div></div>';});$('tracks').innerHTML=html||'<p class="muted small">Add a character, then choose an action to create your first clip.</p>';$('tracks').querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>selectClip(b.dataset.a,b.dataset.c));$('tracks').querySelectorAll('[data-caption]').forEach(b=>b.onclick=()=>{stop();captionId=b.dataset.caption;propId=clipId=poseEdit=null;time=project.captions.find(c=>c.id===captionId).start;refresh();});$('tracks').querySelectorAll('[data-propid]').forEach(b=>b.onclick=()=>{stop();propId=b.dataset.propid;captionId=clipId=poseEdit=null;time=project.props.find(p=>p.id===propId).start;refresh();});}
function num(label,key,val,min,max,step=1){return '<label>'+label+'<input data-key="'+key+'" type="number" min="'+min+'" max="'+max+'" step="'+step+'" value="'+Math.round(val*100)/100+'"></label>';}
function textInput(label,key,val,max=30){return '<label>'+label+'<input data-key="'+key+'" maxlength="'+max+'" value="'+esc(val)+'"></label>';}
function colorInput(key,val){return '<label>Colour<input data-key="'+key+'" type="color" value="'+val+'"></label>';}
function bindFields(obj){$('settings').querySelectorAll('[data-key]').forEach(el=>el.onchange=()=>{let val=el.type==='checkbox'?el.checked:el.type==='number'?clamp(Number(el.value)||Number(el.min),Number(el.min),Number(el.max)):el.value;mutate(()=>obj[el.dataset.key]=val);});}
function renderSettings(){const root=$('settings'),a=selectedActor(),c=selectedClip(),p=project.props.find(p=>p.id===propId),cap=project.captions.find(c=>c.id===captionId);$('clipBadge').hidden=true;
if(p){$('inspectorTitle').textContent='Prop settings';root.innerHTML='<h3 class="clip-title">'+p.type[0].toUpperCase()+p.type.slice(1)+'</h3>'+colorInput('color',p.color)+num('Size','size',p.size,10,200)+'<div class="row">'+num('Start X (%)','x',p.x,0,100)+num('Start Y (%)','y',p.y,0,100)+'</div><div class="row">'+num('End X (%)','toX',p.toX,0,100)+num('End Y (%)','toY',p.toY,0,100)+'</div><div class="row">'+num('Start time (s)','start',p.start,0,570,.1)+num('Move length (s)','duration',p.duration,.2,30,.1)+'</div><p class="small muted">The prop stays visible before and after its movement. Y increases downwards.</p><button id="deleteObject" class="wide danger">Delete prop</button>';bindFields(p);$('deleteObject').onclick=()=>mutate(()=>{project.props=project.props.filter(o=>o.id!==p.id);propId=null;});return;}
if(cap){$('inspectorTitle').textContent='Caption settings';root.innerHTML=textInput('Caption text','text',cap.text,240)+'<div class="row">'+num('Start (s)','start',cap.start,0,570,.1)+num('Duration (s)','duration',cap.duration,.2,30,.1)+'</div>'+num('Vertical position (%)','y',cap.y,5,95)+'<button id="deleteObject" class="wide danger">Delete caption</button>';bindFields(cap);$('deleteObject').onclick=()=>mutate(()=>{project.captions=project.captions.filter(o=>o.id!==cap.id);captionId=null;});return;}
if(!a){$('inspectorTitle').textContent='Start your story';root.innerHTML='<p class="muted">Add a character from Your cast to begin.</p>';return;}
if(!c){$('inspectorTitle').textContent='Character settings';root.innerHTML=textInput('Name','name',a.name)+colorInput('color',a.color)+num('Character size','scale',a.scale,.4,3,.05)+'<div class="row">'+num('Position X (%)','x',a.x,0,100)+num('Position Y (%)','y',a.y,0,100)+'</div><label class="check"><input data-key="flip" type="checkbox" '+(a.flip?'checked':'')+'> Face left for new clips</label><p class="small muted">Choose an action from the library. Existing clips have their own start and end positions.</p><button id="deleteActor" class="wide danger">Delete character</button>';bindFields(a);$('deleteActor').onclick=()=>mutate(()=>{project.actors=project.actors.filter(o=>o.id!==a.id);actorId=clipId=null;});return;}
$('inspectorTitle').textContent='Clip settings';$('clipBadge').hidden=false;$('clipBadge').textContent=String(a.clips.indexOf(c)+1).padStart(2,'0');root.innerHTML='<h3 class="clip-title">'+esc(c.action)+'</h3><p class="small muted" style="margin:0">'+esc(a.name)+' · '+(c.action==='Custom pose'?'Your own movement':'Ready-made action')+'</p>'+num('Duration (seconds)','duration',c.duration,.2,30,.1)+'<div class="row">'+num('Start X (%)','fromX',c.fromX,0,100)+num('End X (%)','toX',c.toX,0,100)+'</div><div class="row">'+num('Start Y (%)','fromY',c.fromY,0,100)+num('End Y (%)','toY',c.toY,0,100)+'</div><label>Movement<select data-key="easing"><option value="smooth" '+(c.easing==='smooth'?'selected':'')+'>Ease in & out</option><option value="linear" '+(c.easing==='linear'?'selected':'')+'>Constant speed</option></select></label><label class="check"><input data-key="flip" type="checkbox" '+(c.flip?'checked':'')+'> Face left</label>'+(c.action==='Custom pose'?'<div class="note">Drag joints on the canvas. The engine blends your start and end poses.</div><div class="segmented"><button id="poseA" class="'+(poseEdit==='a'?'active':'')+'">Start pose</button><button id="poseB" class="'+(poseEdit==='b'?'active':'')+'">End pose</button><button id="posePreview">Preview</button></div><button id="copyPose" class="wide quiet">Copy start pose to end</button>':'<button id="customize" class="wide">Edit as custom pose</button>')+'<button id="matchPrevious" class="wide quiet">Match previous clip’s end position</button><div class="icon-actions"><button id="earlier">← Earlier</button><button id="later">Later →</button><button id="duplicate">Copy</button></div><button id="deleteClip" class="wide danger">Delete clip</button>';bindFields(c);
$('deleteClip').onclick=()=>mutate(()=>{a.clips=a.clips.filter(o=>o.id!==c.id);clipId=null;poseEdit=null;});$('duplicate').onclick=()=>{if(a.clips.length>=200||E.duration(project)>570){toast('Project limit reached.');return;}mutate(()=>{let copy=E.clone(c);copy.id=uid();let dx=copy.toX-copy.fromX,dy=copy.toY-copy.fromY;copy.fromX=c.toX;copy.fromY=c.toY;copy.toX=clamp(copy.fromX+dx,0,100);copy.toY=clamp(copy.fromY+dy,0,100);a.clips.splice(a.clips.indexOf(c)+1,0,copy);clipId=copy.id;poseEdit=null;});};
const move=offset=>{let i=a.clips.indexOf(c),j=i+offset;if(j<0||j>=a.clips.length)return;mutate(()=>{[a.clips[i],a.clips[j]]=[a.clips[j],a.clips[i]];time=a.clips.slice(0,j).reduce((s,c)=>s+c.duration,0);});};$('earlier').disabled=a.clips.indexOf(c)===0;$('later').disabled=a.clips.indexOf(c)===a.clips.length-1;$('earlier').onclick=()=>move(-1);$('later').onclick=()=>move(1);$('matchPrevious').onclick=()=>{let prev=a.clips[a.clips.indexOf(c)-1];if(!prev){toast('This is the first clip.');return;}mutate(()=>{c.fromX=prev.toX;c.fromY=prev.toY;});};
if(c.action==='Custom pose'){['a','b'].forEach(k=>$('pose'+k.toUpperCase()).onclick=()=>{stop();poseEdit=k;let start=a.clips.slice(0,a.clips.indexOf(c)).reduce((s,c)=>s+c.duration,0);time=start+(k==='b'?c.duration:0);refresh();});$('posePreview').onclick=()=>{poseEdit=null;time=a.clips.slice(0,a.clips.indexOf(c)).reduce((s,c)=>s+c.duration,0);togglePlay();refresh();};$('copyPose').onclick=()=>mutate(()=>c.poseB=E.clone(c.poseA));}else $('customize').onclick=()=>mutate(()=>{c.poseA=E.pose(c.action,0,0,c);c.poseB=E.pose(c.action,.5,c.duration/2,c);c.action='Custom pose';poseEdit='a';stop();});}
function togglePlay(){if(recording)return;poseEdit=null;if(playing)stop();else{if(time>=E.duration(project))time=0;playing=true;last=performance.now();$('playBtn').textContent='Ⅱ';$('playBtn').setAttribute('aria-label','Pause animation');}refresh();}
function tick(now){if(playing){let dt=Math.min(.1,(now-last)/1000)*speed;time+=dt;let d=E.duration(project);if(time>=d){if(loop)time%=d;else{time=d;stop();}}draw();}last=now;requestAnimationFrame(tick);}
function point(e){let r=canvas.getBoundingClientRect();return[(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height];}
canvas.addEventListener('pointerdown',e=>{if(recording)return;stop();const [x,y]=point(e);let selected=geometry.find(g=>g.id===actorId&&g.kind==='actor');if(poseEdit&&selected){let nearest=Object.entries(selected.joints).map(([k,p])=>({k,d:Math.hypot(p[0]-x,p[1]-y)})).sort((a,b)=>a.d-b.d)[0];if(nearest.d<24*selected.s){checkpoint();drag={kind:'joint',key:nearest.k,geo:selected};canvas.setPointerCapture(e.pointerId);return;}}
let hit=[...geometry].reverse().find(g=>g.kind==='actor'?Object.values(g.joints).some(p=>Math.hypot(p[0]-x,p[1]-y)<30*g.s)||(Math.abs(x-g.x)<45*g.s&&y<g.y+12&&y>g.y-145*g.s):Math.abs(x-g.x)<g.s*.75&&y>g.y-g.s*1.6&&y<g.y+10);if(!hit)return;checkpoint();let coords=E.transform(project,canvas.width,canvas.height).inverse(x,y);if(hit.kind==='actor'){let same=actorId===hit.id;actorId=hit.id;propId=captionId=null;if(!same){clipId=null;poseEdit=null;}let a=selectedActor(),at=E.clipAt(a,time);if(at&&!poseEdit)clipId=at.clip.id;drag={kind:'actor',a,start:coords,original:E.clone(a),clip:selectedClip()};}else{propId=hit.id;captionId=clipId=poseEdit=null;let p=project.props.find(p=>p.id===propId);drag={kind:'prop',p,start:coords,original:E.clone(p)};}refresh();canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(!drag)return;let [x,y]=point(e),world=E.transform(project,canvas.width,canvas.height).inverse(x,y);if(drag.kind==='joint'){let c=selectedClip(),g=drag.geo;if(c)c[poseEdit==='a'?'poseA':'poseB'][drag.key]=[clamp((x-g.x)/g.s/g.flip,-400,400),clamp((y-g.y)/g.s,-400,400)];}else{let dx=world[0]-drag.start[0],dy=world[1]-drag.start[1],o=drag.original;if(drag.kind==='actor'){if(drag.clip){let c=drag.clip,orig=o.clips.find(k=>k.id===c.id);c.fromX=clamp(orig.fromX+dx,0,100);c.toX=clamp(orig.toX+dx,0,100);c.fromY=clamp(orig.fromY+dy,0,100);c.toY=clamp(orig.toY+dy,0,100);}else{drag.a.x=clamp(o.x+dx,0,100);drag.a.y=clamp(o.y+dy,0,100);}}else{drag.p.x=clamp(o.x+dx,0,100);drag.p.toX=clamp(o.toX+dx,0,100);drag.p.y=clamp(o.y+dy,0,100);drag.p.toY=clamp(o.toY+dy,0,100);}}draw();});
function endDrag(){if(drag){drag=null;finish();}}canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);
function undo(){if(!history.length||recording)return;stop();future.push(E.clone(project));project=history.pop();poseEdit=null;finish();}function redo(){if(!future.length||recording)return;stop();history.push(E.clone(project));project=future.pop();poseEdit=null;finish();}
const glyphs=['○','↝','»','↟','⌁','♫','→','↗','⌞','↘','✧','⌘'];$('actions').innerHTML=E.actions.map((a,i)=>'<button data-action="'+a+'"><span class="glyph" aria-hidden="true">'+glyphs[i]+'</span>'+a+'</button>').join('');document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>addAction(b.dataset.action));$('addActor').onclick=addActor;$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('playBtn').onclick=togglePlay;$('restart').onclick=()=>{stop();time=0;poseEdit=null;refresh();};$('scrubber').oninput=e=>{stop();poseEdit=null;time=Number(e.target.value);draw();};$('loopBtn').onclick=()=>{loop=!loop;$('loopBtn').classList.toggle('active',loop);$('loopBtn').setAttribute('aria-pressed',loop);};$('playSpeed').onchange=e=>speed=Number(e.target.value);
$('title').onchange=e=>mutate(()=>project.title=e.target.value.trim()||'Untitled animation');['aspect','background'].forEach(k=>$(k).onchange=e=>mutate(()=>project[k]=e.target.value));$('zoom').onchange=e=>mutate(()=>project.zoom=Number(e.target.value));$('ground').onchange=e=>mutate(()=>project.ground=e.target.checked);
document.querySelectorAll('[data-prop]').forEach(b=>b.onclick=()=>{if(project.props.length>=100){toast('Up to 100 props per project.');return;}mutate(()=>{let p={id:uid(),type:b.dataset.prop,x:55,y:77,toX:55,toY:77,size:45,color:'#e9a34a',start:0,duration:2};project.props.push(p);propId=p.id;clipId=captionId=poseEdit=null;stop();});});$('addCaption').onclick=()=>{if(project.captions.length>=100){toast('Up to 100 captions per project.');return;}mutate(()=>{let c={id:uid(),text:'Your story goes here',start:Math.min(570,Math.round(time*10)/10),duration:2,y:19};project.captions.push(c);captionId=c.id;propId=clipId=poseEdit=null;stop();});};
$('newProject').onclick=()=>mutate(()=>{stop();project={version:1,title:'Untitled animation',aspect:'wide',background:'paper',zoom:100,ground:true,actors:[],props:[],captions:[]};actorId=clipId=propId=captionId=poseEdit=null;time=0;toast('New project ready. Undo brings back your previous project.');});$('demoProject').onclick=()=>mutate(()=>{stop();project=demo();actorId=project.actors[0].id;clipId=project.actors[0].clips[0].id;propId=captionId=poseEdit=null;time=0;toast('Example loaded. Press Play, then make it your own.');});
function filename(){return(project.title||'animation').replace(/[^a-z0-9_-]+/gi,'-').slice(0,60);}
function download(blob,name){if(!blob){toast('The download could not be created.');return;}let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('saveFile').onclick=()=>{download(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),filename()+'.stickmotion.json');toast('Project file downloaded.');};$('loadFile').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>4000000)throw Error('Project file must be smaller than 4 MB.');let p=validate(JSON.parse(await f.text()));mutate(()=>{stop();project=p;actorId=p.actors[0]?.id;clipId=propId=captionId=poseEdit=null;time=0;});toast('Project opened.');}catch(err){toast(err.message||'Could not open this project.');}e.target.value='';};
$('snapshot').onclick=()=>{let c=document.createElement('canvas');[c.width,c.height]=E.sizes(project.aspect,2);E.render(c.getContext('2d'),project,time);c.toBlob(b=>download(b,filename()+'-frame.png'),'image/png');};
$('helpBtn').onclick=()=>$('helpDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(recording&&b.dataset.close==='exportDialog')return;$(b.dataset.close).close();});$('exportDialog').addEventListener('cancel',e=>{if(recording)e.preventDefault();});$('exportBtn').onclick=()=>{stop();$('exportDetails').textContent=E.duration(project).toFixed(1)+' seconds · '+({wide:'16:9 landscape',tall:'9:16 portrait',square:'1:1 square'}[project.aspect])+' · 30 fps';$('exportDialog').showModal();};
function endRecordingUI(){recording=null;$('startExport').disabled=false;$('quality').disabled=false;$('cancelExport').hidden=true;document.querySelector('[data-close="exportDialog"]').disabled=false;draw();}
$('startExport').onclick=()=>{if(recording)return;if(typeof MediaRecorder==='undefined'||!HTMLCanvasElement.prototype.captureStream){$('exportStatus').textContent='Video recording is unavailable in this browser. Try a current desktop Chrome or Edge, or save a frame instead.';return;}let mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime){$('exportStatus').textContent='WebM recording is unavailable in this browser. Try desktop Chrome or Edge.';return;}
let stream;try{const snapshot=E.clone(project),c=document.createElement('canvas');[c.width,c.height]=E.sizes(snapshot.aspect,Number($('quality').value));let cx=c.getContext('2d');E.render(cx,snapshot,0);stream=c.captureStream(30);let recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:Number($('quality').value)===2?8000000:4000000}),chunks=[],job={recorder,stream,cancelled:false,frame:0,failed:false};recording=job;const total=E.duration(snapshot);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{cancelAnimationFrame(job.frame);stream.getTracks().forEach(t=>t.stop());if(!job.cancelled&&!job.failed&&chunks.length){download(new Blob(chunks,{type:mime}),filename()+'.webm');$('exportStatus').textContent='Your video is ready. Downloaded without a watermark.';$('exportProgress').value=100;}else if(job.cancelled)$('exportStatus').textContent='Recording cancelled. Your project is unchanged.';else $('exportStatus').textContent='Recording failed. Try standard quality or another browser.';endRecordingUI();};recorder.onerror=()=>{job.failed=true;if(recorder.state!=='inactive')recorder.stop();else{stream.getTracks().forEach(t=>t.stop());$('exportStatus').textContent='Recording failed. Please try again.';endRecordingUI();}};
$('startExport').disabled=true;$('quality').disabled=true;$('cancelExport').hidden=false;document.querySelector('[data-close="exportDialog"]').disabled=true;$('exportProgress').hidden=false;$('exportProgress').value=0;$('exportStatus').textContent='Recording… keep this tab visible.';let start=performance.now();recorder.start(250);function frame(now){if(recording!==job||job.cancelled||job.failed)return;let t=Math.min(total,(now-start)/1000);E.render(cx,snapshot,t);E.render(ctx,snapshot,t);$('exportProgress').value=t/total*100;$('exportStatus').textContent='Recording '+t.toFixed(1)+' / '+total.toFixed(1)+' seconds';if(t>=total){recorder.stop();return;}job.frame=requestAnimationFrame(frame);}job.frame=requestAnimationFrame(frame);}catch(err){stream?.getTracks().forEach(t=>t.stop());endRecordingUI();$('exportStatus').textContent='Could not start recording. Try standard quality or another browser.';}};
$('cancelExport').onclick=()=>{if(recording){recording.cancelled=true;cancelAnimationFrame(recording.frame);if(recording.recorder.state!=='inactive')recording.recorder.stop();}};document.addEventListener('visibilitychange',()=>{if(document.hidden&&recording){$('cancelExport').click();toast('Recording cancelled because the tab was hidden. Keep it visible while exporting.');}});
document.addEventListener('keydown',e=>{if(recording||document.querySelector('dialog[open]')||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();togglePlay();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}});
const mc=document.modelContext;if(mc?.registerTool){const life=new AbortController();window.addEventListener('pagehide',()=>life.abort(),{once:true});const register=t=>{try{Promise.resolve(mc.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{}};register({name:'read_animation_project',description:'Read the current visible animation project and its length.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({project:E.clone(project),duration:E.duration(project)})});register({name:'add_animation_action',description:'Append an action clip to the selected character, creating a character if needed.',inputSchema:{type:'object',properties:{action:{type:'string',enum:E.actions}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!E.actions.includes(input.action))throw Error('Choose a supported action.');if(recording)throw Error('Wait until export completes.');let id=addAction(input.action);if(!id)throw Error('The action could not be added.');return {clipId:id,actorId,duration:E.duration(project)};}});}
refresh();save();requestAnimationFrame(tick);
