/* Run with Playwright installed in tests/node_modules. All fixtures are synthetic. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const PDF = require('../studio/vendor/pdf-lib.min.js');
const out = path.resolve(__dirname, 'results');
const fixtures = path.join(out, 'fixtures');
function ff(args, name) { execFileSync('ffmpeg', ['-hide_banner','-loglevel','error','-y',...args,path.join(fixtures,name)]); }
(async()=>{
 await fs.mkdir(fixtures,{recursive:true});
 ff(['-f','lavfi','-i','testsrc2=size=320x180:rate=30','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t','2','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac'],'sample.mp4');
 ff(['-f','lavfi','-i','color=c=green:size=180x320:rate=30','-t','1','-c:v','libx264','-an'],'silent.mp4');
 ff(['-f','lavfi','-i','color=c=red:size=800x400','-frames:v','1'],'sample.png');
 ff(['-f','lavfi','-i','sine=frequency=660:sample_rate=48000','-t','1','-c:a','pcm_s16le'],'music.wav');
 const doc=await PDF.PDFDocument.create();doc.addPage([400,200]).drawText('FIRST PAGE');doc.addPage([300,500]).drawText('SECOND PAGE');await fs.writeFile(path.join(fixtures,'sample.pdf'),await doc.save());
 const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];
 page.on('pageerror',e=>errors.push(e.stack||e.message));page.on('console',m=>{if(m.type()==='error')console.error('Browser console:',m.text());});
 const routes={image:'image-tools',pdf:'pdf-tools',video:'video-tools',design:'design-studio',editor:'video-editor'};
 async function route(key){await page.goto(`http://127.0.0.1:4173/${routes[key]}`);await page.locator('#workspace .tool-layout').waitFor();assert.equal(await page.locator('h1').count(),1);assert.equal(await page.title(),await page.locator('meta[property="og:title"]').getAttribute('content'));assert.equal(await page.locator('.feature-guide details').count(),6);await page.locator('.feature-guide summary').first().click();assert(await page.locator('.feature-guide details').first().evaluate(el=>el.open));await page.locator('.feature-guide summary').first().click();await page.locator('h1').scrollIntoViewIfNeeded();assert.equal(await page.locator('aside').count(),0);assert.equal(await page.locator('.feature-links [aria-current=page]').getAttribute('href'),'/'+routes[key]);}
 async function ready(){await page.waitForFunction(()=>{const s=document.querySelector('#status');return s&&(/ready|failed|could not|cancelled/i.test(s.textContent));},{},{timeout:180000});const s=await page.locator('#status').innerText();assert(!/failed|could not/i.test(s),s);return s;}
 async function save(name){const promise=page.waitForEvent('download');await page.locator('#downloads a').first().click();await(await promise).saveAs(path.join(out,name));}
 try{
  await route('image');await page.locator('#image-file').setInputFiles(path.join(fixtures,'sample.png'));await page.locator('#image-export').waitFor();await page.locator('#image-lock').uncheck();await page.locator('#image-w').fill('200');await page.locator('#image-h').fill('100');await page.locator('#image-format').selectOption('image/png');await page.locator('#image-export').click();await ready();await save('image.png');const png=await fs.readFile(path.join(out,'image.png'));assert.equal(png.readUInt32BE(16),200);assert.equal(png.readUInt32BE(20),100);
  await page.locator('#image-format').selectOption('image/jpeg');await page.locator('#image-target').fill('8');await page.locator('#image-export').click();await ready();await save('image.jpg');assert((await fs.stat(path.join(out,'image.jpg'))).size<=8192);
  await page.screenshot({path:path.join(out,'image-desktop.png'),fullPage:true});console.log('PASS browser image resizing and target-size JPEG export');
  await route('design');await page.locator('#design-template').selectOption('social');await page.locator('#design-apply').click();await page.locator('#layer-text').fill('A tested design');await page.locator('#add-circle').click();await page.locator('#design-undo').click();await page.locator('#design-export').click();await ready();await save('design.png');assert((await fs.stat(path.join(out,'design.png'))).size>1000);await page.screenshot({path:path.join(out,'design-desktop.png'),fullPage:true});console.log('PASS browser design templates, text, layers, undo and PNG export');
  await route('pdf');await page.locator('#pdf-files').setInputFiles(path.join(fixtures,'sample.pdf'));await page.waitForFunction(()=>document.querySelectorAll('.page-card').length===2);await page.getByRole('button',{name:'Move page 2 earlier',exact:true}).click();await page.locator('#pdf-size').selectOption('595.28,841.89');await page.locator('#pdf-export').click();await ready();await save('pages.pdf');let pdf=await PDF.PDFDocument.load(await fs.readFile(path.join(out,'pages.pdf')));assert.equal(pdf.getPageCount(),2);assert.equal(pdf.getPage(0).getWidth(),595.28);
  await page.locator('#pdf-mode').selectOption('split');await page.locator('#pdf-export').click();await ready();await save('pages.zip');assert((await fs.stat(path.join(out,'pages.zip'))).size>100);
  await page.locator('#pdf-mode').selectOption('merge');await page.locator('#pdf-compression').selectOption('raster');await page.locator('#pdf-export').click();await ready();await save('compressed.pdf');pdf=await PDF.PDFDocument.load(await fs.readFile(path.join(out,'compressed.pdf')));assert.equal(pdf.getPageCount(),2);console.log('PASS browser PDF reorder, resize, ZIP split and raster compression');
  await route('editor');await page.locator('#video-files').setInputFiles([path.join(fixtures,'sample.mp4'),path.join(fixtures,'silent.mp4')]);await page.waitForFunction(()=>document.querySelectorAll('.clip').length===2);await page.locator('#video-text').fill('Export test');await page.locator('#video-transition').selectOption('fade');await page.locator('#video-music').setInputFiles(path.join(fixtures,'music.wav'));await page.locator('#video-w').fill('320');await page.locator('#video-h').fill('180');await page.screenshot({path:path.join(out,'video-desktop.png'),fullPage:true});await page.locator('#video-export').click();await ready();await save('timeline.mp4');let info=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',path.join(out,'timeline.mp4')]));assert.equal(info.streams.find(s=>s.codec_type==='video').width,320);assert(Math.abs(Number(info.format.duration)-3)<.25);assert(info.streams.some(s=>s.codec_type==='audio'));
  await page.locator('#video-format').selectOption('webm');await page.locator('#video-export').click();await ready();await save('timeline.webm');console.log('PASS browser FFmpeg WASM timeline export: text, fades, music, mixed audio/silent clips, MP4 and WebM');
  await route('video');await page.locator('#video-files').setInputFiles(path.join(fixtures,'sample.mp4'));await page.waitForFunction(()=>!document.querySelector('#video-export').disabled);await page.locator('#video-start').fill('0.5');await page.locator('#video-start').press('Tab');await page.locator('#video-end').fill('1.5');await page.locator('#video-end').press('Tab');await page.locator('#video-w').fill('180');await page.locator('#video-h').fill('320');await page.locator('#video-fit').selectOption('cover');await page.locator('#video-export').click();await ready();await save('trimmed.mp4');info=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',path.join(out,'trimmed.mp4')]));assert.equal(info.streams.find(s=>s.codec_type==='video').height,320);assert(Math.abs(Number(info.format.duration)-1)<.2);console.log('PASS browser trim and portrait crop export');await page.locator('#video-export').click();await page.locator('#video-cancel').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('cancelled')&&!document.querySelector('#video-export').disabled);console.log('PASS export cancellation restores editing');
  // Verify navigation on the original pages without changing their tool content.
  for(const width of [1440,1024,390]){await page.setViewportSize({width,height:900});for(const url of ['/','/pdf']){await page.goto('http://127.0.0.1:4173'+url);await page.locator('h1').waitFor();assert.equal(await page.locator('.creative-tools-bar').count(),0);if(width===390){await page.getByRole('button',{name:'All tools'}).click();assert.equal(await page.getByRole('button',{name:'All tools'}).getAttribute('aria-expanded'),'true');}for(const slug of Object.values(routes)){assert(await page.locator(`.feature-links a[href="/${slug}"]`).isVisible());}assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'navigation overflow');await page.screenshot({path:path.join(out,`navigation-${url==='/'?'home':'pdf'}-${width}.png`),fullPage:false});}}
  for(const [key,slug] of Object.entries(routes)){await page.goto('http://127.0.0.1:4173/studio#'+key);await page.waitForURL('**/'+slug);await page.locator('h1').waitFor();}
  console.log('PASS separate pages, legacy links, desktop and mobile navigation');
  await page.setViewportSize({width:390,height:844});for(const key of ['image','pdf','design','video','editor']){await route(key);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`${key} mobile overflow`);}await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});assert.deepEqual(errors,[]);console.log('PASS five mobile layouts and no page errors');
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});await fs.writeFile(path.join(out,'failure.txt'),`${e.stack}\n\nPage errors: ${errors.join('\n')}\n\n${await page.locator('body').innerText()}`);throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
