export const $ = (s, root=document) => root.querySelector(s);
export const $$ = (s, root=document) => [...root.querySelectorAll(s)];
export const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const bytes = n => n<1024 ? `${n} B` : n<1048576 ? `${(n/1024).toFixed(1)} KB` : `${(n/1048576).toFixed(2)} MB`;
export const baseName = s => s.replace(/\.[^.]+$/, '');
export const uid = () => crypto.randomUUID();
export function number(value,min,max,name='Value'){const n=Number(value);if(!Number.isFinite(n)||n<min||n>max)throw Error(`${name} must be between ${min} and ${max}.`);return n;}
export function dimensions(w,h,max=4096){w=Math.round(number(w,1,max,'Width'));h=Math.round(number(h,1,max,'Height'));if(w*h>16777216)throw Error('Please use a canvas of 16 megapixels or less.');return {w,h};}
export function status(text,error=false){const s=$('#status');if(s){s.textContent=text;s.classList.toggle('error',error);}}
export function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.textContent=`Download ${name} · ${bytes(blob.size)}`;$('#downloads').append(a);return a;}
export function clearDownloads(){ $$('#downloads a').forEach(a=>URL.revokeObjectURL(a.href));$('#downloads')?.replaceChildren(); }
export function shell(title,description,body){return `${document.querySelector(".feature-intro")?'':`<h1>${title}</h1><p class="intro">${description}</p>`}${body}<div id="status" class="status" role="status" aria-live="polite"></div><div class="downloads" id="downloads"></div>`;}
export function upload(id,accept,title,detail,multiple=false){return `<label class="upload" id="${id}-drop"><strong>${title}</strong><small>${detail}</small><input id="${id}" type="file" accept="${accept}" ${multiple?'multiple':''}></label>`;}
export function wireUpload(id,handler){const input=$(`#${id}`),zone=$(`#${id}-drop`);const run=files=>{if(files.length)Promise.resolve(handler([...files])).catch(e=>status(e.message,true));};input.onchange=()=>{run(input.files);input.value='';};zone.ondragover=e=>{e.preventDefault();zone.classList.add('dragging');};zone.ondragleave=()=>zone.classList.remove('dragging');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('dragging');if(!input.disabled)run(e.dataTransfer.files);};}
export async function bitmap(file){if(!/^image\/(png|jpeg|webp)$/.test(file.type))throw Error('Choose a JPG, PNG or WebP image.');return createImageBitmap(file);}
export function canvasBlob(canvas,type='image/png',quality=.9){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Your browser could not export this image.')),type,quality));}
export function drawFit(ctx,img,w,h,mode='contain',cx=.5,cy=.5){const iw=img.videoWidth||img.naturalWidth||img.width,ih=img.videoHeight||img.naturalHeight||img.height;if(!iw||!ih)return;const scale=(mode==='cover'?Math.max:Math.min)(w/iw,h/ih);const dw=iw*scale,dh=ih*scale;ctx.drawImage(img,(w-dw)*cx,(h-dh)*cy,dw,dh);}
export async function metadata(file){const url=URL.createObjectURL(file),v=document.createElement('video');v.preload='metadata';v.src=url;try{await new Promise((res,rej)=>{v.onloadedmetadata=res;v.onerror=()=>rej(Error(`Cannot read ${file.name}. Try an MP4 or WebM file.`));});if(!Number.isFinite(v.duration)||v.duration<=0)throw Error('This video has no readable duration.');return {url,duration:v.duration,w:v.videoWidth,h:v.videoHeight};}catch(e){URL.revokeObjectURL(url);throw e;}finally{v.removeAttribute('src');v.load();}}
export function fitFilter(w,h,mode='contain',cx=.5,cy=.5){return mode==='cover'?`scale=${w}:${h}:force_original_aspect_ratio=increase,crop=${w}:${h}:(iw-ow)*${cx}:(ih-oh)*${cy},setsar=1`:`scale=${w}:${h}:force_original_aspect_ratio=decrease,pad=${w}:${h}:(ow-iw)/2:(oh-ih)/2:black,setsar=1`;}
export function presetSelect(id){return `<label>Size preset<select id="${id}"><option value="custom">Custom dimensions</option><option value="1080,1920">Reels / Shorts · 1080 × 1920</option><option value="1920,1080">YouTube · 1920 × 1080</option><option value="1080,1080">Square post · 1080 × 1080</option><option value="1080,1350">Portrait post · 1080 × 1350</option><option value="1280,720">Thumbnail · 1280 × 720</option></select></label>`;}
