import {escape as esc} from './icons.js';
import {CREDIT_PLANS,PRICE_EXAMPLES,quoteCredits,formatINR,formatUSD} from './pricing.js';
import {getBillingConfig,unavailableBilling} from './config.js';
export async function mountBilling(view,{jobs,toast,cloudState,cloudRequest}) {
  let info=unavailableBilling();
  function draw(){
    const offers=info.plans?.length?info.plans:CREDIT_PLANS,user=cloudState().user;
    const rows=PRICE_EXAMPLES.map(([label,endpoint,input])=>{const q=quoteCredits(endpoint,input,info.usdInr||null);return `<tr><td>${esc(label)}</td><td>${formatUSD(q.providerUsd)}</td><td>${formatUSD(q.retailUsd)}</td>${info.usdInr?`<td>${formatINR(q.retailInr)}</td>`:''}</tr>`;}).join('');
    view.innerHTML=`<div class="page billing-page"><div class="page-head"><div><span class="eyebrow">CREATE AT YOUR OWN PACE</span><h1>Simple pay-as-you-go</h1><p>The same creative tools. A balance that fits your next project.</p></div><a href="#account" class="outline-button">${user?'My account':'Sign in / Create account'}</a></div>
      <div class="commerce-banner"><div><strong>${info.testMode?'Checkout testing':info.enabled?'Your next idea starts here':'AI plans — coming soon'}</strong><p>${info.testMode?'Test payments do not fund real generation.':info.enabled?'Pay once and create with your balance.':'We are configuring payments and testing AI generation. Purchases and paid generation are not available yet.'}</p></div><span class="tag">${info.enabled?'PAY ONCE':'LAUNCH IN PREPARATION'}</span></div>
      <div class="pricing-grid"><article class="panel price-card"><span class="eyebrow">CREATE & EDIT</span><h2>Free</h2><div class="price-amount">₹0</div><p>Your creative toolkit, ready today.</p><ul><li>Photo, vector, video, RAW, PDF, motion and layout editors</li><li>Canvas drawing, 3D scenes and world viewing</li><li>Moodboards, frame extraction and downloads</li><li>Sign in for private cloud storage</li></ul><a href="#home" class="outline-button">Explore free tools</a></article>
      ${offers.map(p=>`<article class="panel price-card ${p.id==='topup-500'?'featured-price':''}"><span class="eyebrow">ONE-TIME BALANCE</span><h2>${esc(p.name)}</h2><div class="price-amount">${formatINR(p.amountCents/100)}</div><p>${formatINR(p.amountCents/100)} of AI generation balance.</p><ul><li>Images and AI image editing</li><li>Text / image to video, with supported duration and audio controls</li><li>Music with lyrics, style and supported length controls</li><li>All free creative tools included</li><li>No monthly subscription; unused balance does not expire</li></ul><button class="primary-button" data-checkout="${esc(p.id)}" ${!p.available?'disabled':''}>${p.available?'Add '+formatINR(p.amountCents/100):'Coming soon'}</button></article>`).join('')}</div>
      <section class="plan-storage-note"><h2>Private storage. Clear limits.</h2><p>Every signed-in account includes <strong>500 MB of cloud media storage</strong>, up to 150 MB per file. Cloud files and synced projects are available for <strong>30 days from first save</strong>. The library shows expiry dates. Download or back up your work before expiry; your account and unused AI balance stay available.</p><p>All three balances unlock the same supported AI capabilities after launch. They buy different amounts of generation, not different tool bundles. Output count, model, resolution and duration determine how much each request uses. 3D/world generation, AI video VFX, speech and sound effects are planned separately and are not included in the initial AI launch.</p></section>
      <div class="settings-grid billing-details"><section class="panel"><h2>Generation cost + 20%</h2><p>Our generation price is the reviewed provider cost × 1.20, converted to INR and rounded up once to the next paise. Review the final price before generating.</p><div class="table-scroll"><table class="credit-table"><thead><tr><th>Generation</th><th>Provider cost</th><th>Our price (USD)</th>${info.usdInr?'<th>You pay (INR)</th>':''}</tr></thead><tbody>${rows}</tbody></table></div><p>${info.usdInr?`Conversion: $1 = ${formatINR(info.usdInr)} · ${esc(info.fxDate||'')} · ${esc(info.fxSource||'daily reference rate')}.`:'INR conversion is loading or temporarily unavailable. Purchases and paid generation remain unavailable without a current rate.'}</p><p>Single-output examples. Search, thinking, native audio and voice controls can change the price. Initial supported models: FLUX Schnell, Nano Banana 2, Kling 2.6, ACE-Step and MiniMax Music 2. Confirmed failed generations return the reserved balance.</p></section>
      <section class="panel"><h2>Your prepaid balance</h2><div id="billing-wallet">${user?'Loading your balance…':'Sign in to see your prepaid balance.'}</div><p>No API key is needed. Your account, balance and private library work together.</p><a href="#account" class="primary-button">${user?'Manage account & storage':'Create your account'}</a><div class="divider"></div><h2>What stays free?</h2><p>Local editing, canvas drawing, scenes, moodboards, frame extraction and downloads. Paid AI generation uses your balance after launch.</p><p>${jobs.length} submitted jobs · ${jobs.filter(j=>j.status==='COMPLETED').length} completed</p><p>Payments use Razorpay. The shown amount is the checkout total, with no automatic renewal.</p><a class="text-link" href="/creative-studio-pricing">Read full plan details ↗</a></section></div></div>`;
    view.querySelectorAll('[data-checkout]').forEach(b=>b.onclick=()=>{if(!cloudState().user){location.hash='account';return;}location.assign('/payments/checkout?pack='+encodeURIComponent(b.dataset.checkout));});
    if(user)cloudRequest('/functions/v1/convertshorts-billing').then(d=>{const wallet=view.querySelector('#billing-wallet');if(wallet&&cloudState().user?.id===user.id)wallet.textContent=formatINR(d.balanceInr??(d.credits||0)/100);}).catch(()=>{const wallet=view.querySelector('#billing-wallet');if(wallet)wallet.textContent='Your balance is temporarily unavailable. Please try again.';});
  }
  draw();
  info=await getBillingConfig();if(location.hash.split('?')[0]==='#billing')draw();
}
