import {escape as esc} from './icons.js';
import {CREDIT_PLANS,CREDIT_USD} from './pricing.js';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
export async function mountBilling(view,{jobs,toast,cloudState,cloudRequest}) {
  let info={enabled:false,plans:CREDIT_PLANS};
  try{const r=await fetch('/api/billing?action=config');if(r.ok)info=await r.json();}catch{}
  const offers=info.plans?.length?info.plans:CREDIT_PLANS;
  const user=cloudState().user;
  view.innerHTML=`<div class="page"><div class="page-head"><div><h1>Pricing & credits</h1><p>Free local tools. Clear prices for AI generation.</p></div><a href="#settings" class="outline-button">Use your own API key</a></div>
    <div class="commerce-banner"><div><strong>${info.enabled?'Create with ConvertShorts credits':'Hosted AI credits — coming soon'}</strong><p>${info.enabled?'Sign in, choose a plan, and generate without connecting a provider key.':'The planned prices are shown below. Local tools and your own funded provider key are available today.'}</p></div><a href="#account" class="outline-button">${user?'Your account':'Sign in'}</a></div>
    <div class="pricing-grid"><article class="panel price-card"><span class="eyebrow">LOCAL TOOLS</span><h2>Free</h2><div class="price-amount">$0</div><p>Edit your own files in the browser.</p><ul><li>Seven professional browser editors</li><li>AI Canvas drawing and composition</li><li>3D scene composition and world viewing</li><li>Moodboards, frame extraction and local library</li></ul><a href="#home" class="outline-button">Open the studio</a></article>
    ${offers.filter(p=>p.mode==='subscription').map(p=>`<article class="panel price-card"><span class="eyebrow">${p.available?'HOSTED AI':'PLANNED HOSTED AI'}</span><h2>${esc(p.name)}</h2><div class="price-amount">${money(p.amountCents/100)}<small>/ month</small></div><p>${Number(p.credits).toLocaleString()} credits each month</p><ul><li>Generation charged by model and settings</li><li>See the credit price before submitting</li><li>Credits returned for confirmed failed jobs</li><li>Monthly credits expire at the end of their period</li></ul><button class="primary-button" data-checkout="${esc(p.id)}" ${!p.available?'disabled':''}>${p.available?'Choose '+esc(p.name):'Coming soon'}</button></article>`).join('')}</div>
    <div class="settings-grid billing-details"><section class="panel"><h2>What does a generation cost?</h2><p>One ConvertShorts credit is ${money(CREDIT_USD)} of generation value. Credits are specific to this service.</p><div class="table-scroll"><table class="credit-table"><thead><tr><th>Generation</th><th>Credits</th><th>Value</th></tr></thead><tbody>${[['FLUX Schnell · 1 image',1],['Nano Banana 2 · 1K image',10],['Nano Banana 2 · 2K image',15],['Nano Banana 2 · 4K image',20],['Kling 2.6 Pro · 5 seconds · no audio',44],['Kling 2.6 Pro · 5 seconds · audio',88],['Kling 2.6 Pro · 10 seconds · audio',175]].map(([label,c])=>`<tr><td>${label}</td><td>${c}</td><td>${money(c*CREDIT_USD)}</td></tr>`).join('')}</tbody></table></div><p>Text and image-to-video use the same listed rates. Output count and resolution change the credit price. Other models currently use your own provider key. Review the current quote in the composer.</p></section>
    <section class="panel"><h2>Your credits</h2><div id="billing-wallet">${user?'Loading your balance…':'Sign in to see your hosted credit balance.'}</div><button class="outline-button" id="billing-portal" ${!info.enabled||!user?'disabled':''}>Manage subscription</button><div class="divider"></div><h2>Top up without a subscription</h2>${offers.filter(p=>p.mode==='payment').map(p=>`<p>${money(p.amountCents/100)} · ${Number(p.credits).toLocaleString()} credits · no expiry</p><button class="outline-button" data-checkout="${esc(p.id)}" ${!p.available?'disabled':''}>${p.available?'Buy credit pack':'Coming soon'}</button>`).join('')}<p>Listed prices are in USD. Checkout shows the final total.</p><div class="divider"></div><h2>Your own provider account</h2><p>Own-key requests use your provider balance and are billed directly by that provider. They do not spend ConvertShorts credits.</p><p>${jobs.length} submitted jobs · ${jobs.filter(j=>j.status==='COMPLETED').length} completed</p><a class="text-link" href="https://fal.ai/dashboard/billing" target="_blank" rel="noopener">Fal billing ↗</a></section></div></div>`;
  view.querySelectorAll('[data-checkout]').forEach(b=>b.onclick=async()=>{if(!cloudState().user){location.hash='account';return;}b.disabled=true;try{const d=await cloudRequest('/functions/v1/convertshorts-billing',{method:'POST',body:{action:'checkout',plan:b.dataset.checkout}});location.assign(d.url);}catch(e){toast(e.message);b.disabled=false;}});
  view.querySelector('#billing-portal').onclick=async()=>{try{const d=await cloudRequest('/functions/v1/convertshorts-billing',{method:'POST',body:{action:'portal'}});location.assign(d.url);}catch(e){toast(e.message);}};
  if(user)try{const d=await cloudRequest('/functions/v1/convertshorts-billing');const wallet=view.querySelector('#billing-wallet');if(wallet&&cloudState().user?.id===user.id)wallet.textContent=(d.credits||0)+' credits · '+(d.plan||'Free');}catch{const wallet=view.querySelector('#billing-wallet');if(wallet)wallet.textContent='The balance is temporarily unavailable. Your own-key requests still use provider billing.';}
}
