import {escape as esc} from './icons.js';
import {CREDIT_PLANS,PRICE_EXAMPLES,quoteCredits,formatINR,formatUSD} from './pricing.js';
export async function mountBilling(view,{jobs,toast,cloudState,cloudRequest}) {
  let info={enabled:false,plans:CREDIT_PLANS,usdInr:null};
  try{const r=await fetch('/api/billing?action=config');if(r.ok)info=await r.json();}catch{}
  const offers=info.plans?.length?info.plans:CREDIT_PLANS,user=cloudState().user;
  const rows=PRICE_EXAMPLES.map(([label,endpoint,input])=>{const q=quoteCredits(endpoint,input,info.usdInr||null);return `<tr><td>${esc(label)}</td><td>${formatUSD(q.providerUsd)}</td><td>${formatUSD(q.retailUsd)}</td>${info.usdInr?`<td>${formatINR(q.retailInr)}</td>`:''}</tr>`;}).join('');
  view.innerHTML=`<div class="page"><div class="page-head"><div><h1>Simple pay-as-you-go</h1><p>Free creative tools. Add a small balance when you need AI.</p></div><a href="#settings" class="outline-button">Use your own Fal key</a></div>
    <div class="commerce-banner"><div><strong>${info.testMode?'Razorpay test mode':info.enabled?'Top up and start creating':'Prepaid AI — coming soon'}</strong><p>${info.testMode?'Test payments verify checkout and do not fund real AI generation.':info.enabled?'Pay once. Use your balance for images, videos and music. No monthly subscription.':'Prepaid amounts are shown below. Free tools and your own funded Fal key work today.'}</p></div><a href="#account" class="outline-button">${user?'Your account':'Sign in'}</a></div>
    <div class="pricing-grid"><article class="panel price-card"><span class="eyebrow">CREATIVE TOOLS</span><h2>Free</h2><div class="price-amount">₹0</div><p>Work with your own media and your own AI account.</p><ul><li>All local creative editors</li><li>AI Canvas, scenes and moodboards</li><li>Frame extraction and local library</li><li>Own-key AI billed directly by Fal</li></ul><a href="#home" class="outline-button">Open the studio</a></article>
    ${offers.map(p=>`<article class="panel price-card"><span class="eyebrow">ONE-TIME TOP-UP</span><h2>${esc(p.name)}</h2><div class="price-amount">${formatINR(p.amountCents/100)}</div><p>${formatINR(p.amountCents/100)} of generation balance</p><ul><li>No subscription or automatic renewal</li><li>Prepaid balance does not expire</li><li>See the price before generating</li><li>Confirmed failed jobs return the balance</li></ul><button class="primary-button" data-checkout="${esc(p.id)}" ${!p.available?'disabled':''}>${p.available?'Add '+formatINR(p.amountCents/100):'Coming soon'}</button></article>`).join('')}</div>
    <div class="settings-grid billing-details"><section class="panel"><h2>Fal cost + 20%</h2><p>Our generation price is the published Fal cost × 1.20. INR charges round up to the next paise. Duration, audio, resolution and output count affect the price.</p><div class="table-scroll"><table class="credit-table"><thead><tr><th>Generation</th><th>Fal cost</th><th>Our price (USD)</th>${info.usdInr?'<th>You pay (INR)</th>':''}</tr></thead><tbody>${rows}</tbody></table></div><p>${info.usdInr?`Conversion: $1 = ${formatINR(info.usdInr)} · ${esc(info.fxDate||'')} · ${esc(info.fxSource||'daily reference rate')}.`:'Current INR conversion is temporarily unavailable. USD comparisons remain visible; hosted generation stays unavailable until a current rate returns.'}</p><p>These are single-output examples. Search, high thinking and voice control can add costs. Nano Banana image editing uses the same image rates. Other models currently require your own provider key. The composer shows the final request price.</p><details class="workflow-help"><summary>View Fal price sources</summary><div>${[...new Set(PRICE_EXAMPLES.map(([,endpoint])=>endpoint))].map(endpoint=>`<p><a class="text-link" href="https://fal.ai/models/${endpoint}" target="_blank" rel="noopener">${esc(endpoint)} ↗</a></p>`).join('')}</div></details></section>
    <section class="panel"><h2>Your prepaid balance</h2><div id="billing-wallet">${user?'Loading your balance…':'Sign in to see your prepaid balance.'}</div><p>Top-ups pay for AI generation through our provider account. They are specific to ConvertShorts.</p><div class="divider"></div><h2>Already have a Fal account?</h2><p>Connect your own funded API key and use the studio free. Fal bills your account directly and no ConvertShorts balance is spent.</p><p>${jobs.length} submitted jobs · ${jobs.filter(j=>j.status==='COMPLETED').length} completed</p><a class="text-link" href="#settings">Connect AI →</a><p>Payments use Razorpay. The amount shown is the checkout total. There are no recurring charges.</p></section></div></div>`;
  view.querySelectorAll('[data-checkout]').forEach(b=>b.onclick=()=>{if(!cloudState().user){location.hash='account';return;}location.assign('/payments/checkout?pack='+encodeURIComponent(b.dataset.checkout));});
  if(user)try{const d=await cloudRequest('/functions/v1/convertshorts-billing');const wallet=view.querySelector('#billing-wallet');if(wallet&&cloudState().user?.id===user.id)wallet.textContent=formatINR(d.balanceInr??(d.credits||0)/100);}catch{const wallet=view.querySelector('#billing-wallet');if(wallet)wallet.textContent='The balance is temporarily unavailable. Your own Fal key remains available.';}
}
