import {icon,escape as esc} from './icons.js';
import {all,put,uid,importFile,downloadBlob} from './storage.js';
export async function mountBoard(view,{toast,assetURL}){
 let boards=(await all('boards')).filter(b=>b.kind!=='scene'),assets=await all('assets'),board=boards.sort((a,b)=>b.updated-a.updated)[0]||{id:uid(),name:'Untitled moodboard',nodes:[],updated:Date.now()},saveTimer;
 view.innerHTML=`<div class="page"><div class="page-head"><div><h1>Moodboard</h1><p>References, notes and visual direction in one place. Drag cards to arrange your board.</p></div><button class="outline-button" id="new-board">+ New board</button></div><div class="board-toolbar"><input id="board-name" aria-label="Moodboard name" value="${esc(board.name)}"><select id="board-select" aria-label="Open moodboard" style="width:190px"><option value="${board.id}">${esc(board.name)}</option>${boards.filter(b=>b.id!==board.id).map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select><button class="outline-button" id="add-note">${icon('plus',15)} Note</button><label class="outline-button">${icon('image',15)} Image<input id="board-upload" type="file" accept="image/*" multiple hidden></label><button class="outline-button" id="board-export">${icon('download',15)} Export PNG</button><span id="board-save-state">Saved locally</span></div><div class="board-workspace" id="board-canvas"></div></div>`;
 const el=id=>view.querySelector('#'+id),stage=el('board-canvas');
 const save=()=>{el('board-save-state').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{board.name=el('board-name').value.trim()||'Untitled moodboard';board.updated=Date.now();await put('boards',board);el('board-save-state').textContent='Saved locally';}catch(e){toast('Could not save: '+e.message);}},250);};
 const offset=()=>({x:35+board.nodes.length%4*245,y:35+Math.floor(board.nodes.length/4)*210});
 function render(){stage.innerHTML=board.nodes.map(n=>{const a=assets.find(a=>a.id===n.asset);return `<article class="board-node ${n.type==='image'?'image-node':''}" style="left:${n.x}px;top:${n.y}px;width:${n.width||220}px" data-node="${n.id}"><header><span>${n.type==='image'?'REFERENCE':'NOTE'}</span><button data-remove-node="${n.id}" aria-label="Remove card">×</button></header>${a?`<img src="${esc(assetURL(a))}" alt="${esc(a.name)}">`:`<textarea data-note="${n.id}" aria-label="Moodboard note">${esc(n.text||'')}</textarea>`}</article>`;}).join('');if(!board.nodes.length)stage.innerHTML='<div class="empty-state" style="min-height:550px;border:0;pointer-events:none"><h2>Give your idea a place to grow</h2><p>Add an image or note, then arrange your visual direction.</p></div>';}
 stage.addEventListener('input',e=>{if(e.target.dataset.note){board.nodes.find(n=>n.id===e.target.dataset.note).text=e.target.value;save();}});
 stage.addEventListener('click',e=>{const b=e.target.closest('[data-remove-node]');if(b){board.nodes=board.nodes.filter(n=>n.id!==b.dataset.removeNode);render();save();}});
 let drag=null;stage.addEventListener('pointerdown',e=>{const node=e.target.closest('[data-node]');if(!node||e.target.closest('textarea,button'))return;const item=board.nodes.find(n=>n.id===node.dataset.node);drag={node,item,startX:e.clientX,startY:e.clientY,x:item.x,y:item.y};node.setPointerCapture(e.pointerId);e.preventDefault();});stage.addEventListener('pointermove',e=>{if(!drag)return;drag.item.x=Math.max(0,drag.x+e.clientX-drag.startX);drag.item.y=Math.max(0,drag.y+e.clientY-drag.startY);drag.node.style.left=drag.item.x+'px';drag.node.style.top=drag.item.y+'px';});stage.addEventListener('pointerup',()=>{if(drag){drag=null;save();}});
 el('add-note').onclick=()=>{board.nodes.push({id:uid(),type:'note',text:'',...offset()});render();save();};el('board-name').oninput=save;
 el('board-upload').onchange=async e=>{try{for(const file of e.target.files){const a=await importFile(file);assets.push(a);board.nodes.push({id:uid(),type:'image',asset:a.id,...offset()});}render();save();}catch(e){toast(e.message);}};
 el('new-board').onclick=async()=>{await put('boards',board);board={id:uid(),name:'Untitled moodboard',nodes:[],updated:Date.now()};await put('boards',board);el('board-name').value=board.name;const option=new Option(board.name,board.id);el('board-select').add(option);el('board-select').value=board.id;render();save();};
 el('board-select').onchange=async e=>{await put('boards',board);board=(await all('boards')).find(b=>b.id===e.target.value);el('board-name').value=board.name;render();};
 el('board-export').onclick=async()=>{try{const width=Math.min(6000,Math.max(1200,...board.nodes.map(n=>n.x+(n.width||220)+35))),height=Math.min(6000,Math.max(800,...board.nodes.map(n=>n.y+360)));const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.fillStyle='#17191e';ctx.fillRect(0,0,width,height);ctx.font='24px Arial';ctx.fillStyle='#d8e0f7';ctx.fillText(board.name,30,30);for(const node of board.nodes){const y=node.y+45,w=node.width||220;if(node.type==='image'){const a=assets.find(a=>a.id===node.asset);if(!a)continue;const image=new Image();image.crossOrigin='anonymous';image.src=assetURL(a);await image.decode();ctx.drawImage(image,node.x,y,w,image.height/image.width*w);}else{ctx.fillStyle='#e3dcc6';ctx.fillRect(node.x,y,w,190);ctx.fillStyle='#292923';ctx.font='14px Arial';let lines=[],line='';for(const word of (node.text||'').split(/\s+/)){if(ctx.measureText(line+' '+word).width>w-30){lines.push(line);line=word;}else line+=(line?' ':'')+word;}lines.push(line);lines.slice(0,9).forEach((t,i)=>ctx.fillText(t,node.x+15,y+27+i*18));}}const blob=await new Promise(resolve=>canvas.toBlob(resolve));if(blob)downloadBlob(blob,board.name.replace(/[^a-zA-Z0-9-]/g,'-')+'.png');}catch(e){toast('Could not export the board. Download remote references locally, then retry.');}};
 render();return ()=>{clearTimeout(saveTimer);board.name=el('board-name')?.value.trim()||board.name;board.updated=Date.now();put('boards',board).catch(e=>toast(e.message));};
}
