import {scopedStorage,all,get,put,uid,downloadBlob,referenceData} from './storage.js';
import {escape as esc} from './icons.js';
export async function mountCanvas(view,{toast,asset,onAsset,onReference}){
 const {all,get,put}=scopedStorage();
 view.innerHTML=`<section><div class="scene-toolbar"><strong>AI Canvas</strong><button id="canvas-undo">Undo</button><button id="canvas-redo">Redo</button><label class="outline-button">Import image<input id="canvas-file" type="file" accept="image/*" hidden></label><button id="canvas-export">Export PNG</button><button id="canvas-generate">Use composition in AI</button><button id="canvas-inpaint">Edit masked region with AI</button></div><div class="canvas-layout"><aside class="scene-side"><h3>TOOLS</h3>${['select','brush','eraser','rectangle','ellipse','text','mask'].map(t=>`<button data-canvas-tool="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}<label>Color<input id="canvas-color" type="color" value="#879dff"></label><label>Brush size<input id="canvas-brush" type="range" min="1" max="150" value="12"></label><label>Canvas size<select id="canvas-size"><option value="1024,1024">Square · 1024</option><option value="1536,864">Landscape · 16:9</option><option value="864,1536">Portrait · 9:16</option><option value="1200,800">Landscape · 3:2</option></select></label><button id="canvas-new">New canvas</button><h3>LAYERS</h3><div id="canvas-layers"></div><button id="canvas-layer-up">Move layer forward</button><button id="canvas-layer-delete">Delete selected layer</button><p class="small-note">Draw a mask in white over the area to remove. The AI mask editor uses your composition and mask together.</p></aside><div class="canvas-area"><canvas id="ai-canvas" width="1024" height="1024"></canvas></div></div></section>`;
 const el=id=>view.querySelector('#'+id),canvas=el('ai-canvas'),ctx=canvas.getContext('2d');let tool='select',layers=[],selected=null,pointer=null,history=[],cursor=-1,disposed=false,timer;const images=new Map(),mask=document.createElement('canvas');mask.width=1024;mask.height=1024;const mctx=mask.getContext('2d');
 async function save(){await put('boards',{id:'canvas-current',kind:'canvas',name:'AI Canvas',nodes:[],width:canvas.width,height:canvas.height,layers,mask:mask.toDataURL(),updated:Date.now()});}
 function snapshot(){const data=JSON.stringify({layers,width:canvas.width,height:canvas.height,mask:mask.toDataURL()});history=history.slice(0,cursor+1);history.push(data);if(history.length>30)history.shift();cursor=history.length-1;clearTimeout(timer);timer=setTimeout(()=>save().catch(e=>toast(e.message)),500);}
 async function restore(index){if(index<0||index>=history.length)return;const data=JSON.parse(history[index]);layers=data.layers;cursor=index;canvas.width=data.width||canvas.width;canvas.height=data.height||canvas.height;mask.width=canvas.width;mask.height=canvas.height;const image=await imageFrom(data.mask);mctx.clearRect(0,0,mask.width,mask.height);mctx.drawImage(image,0,0);await loadImages();draw();layerList();}
 const imageFrom=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src;});
 async function loadImages(){for(const l of layers)if(l.src&&!images.has(l.id))images.set(l.id,await imageFrom(l.src));}
 function draw(exporting=false){ctx.clearRect(0,0,canvas.width,canvas.height);for(const l of layers){if(l.hidden)continue;ctx.save();if(l.type==='image')ctx.drawImage(images.get(l.id),l.x,l.y,l.w,l.h);else if(l.type==='rectangle'){ctx.fillStyle=l.color;ctx.fillRect(l.x,l.y,l.w,l.h);}else if(l.type==='ellipse'){ctx.fillStyle=l.color;ctx.beginPath();ctx.ellipse(l.x+l.w/2,l.y+l.h/2,Math.abs(l.w/2),Math.abs(l.h/2),0,0,Math.PI*2);ctx.fill();}else if(l.type==='text'){ctx.fillStyle=l.color;ctx.font=`600 ${l.size}px Arial`;ctx.fillText(l.text,l.x,l.y+l.size);}else if(l.type==='stroke'){ctx.globalCompositeOperation=l.erase?'destination-out':'source-over';ctx.strokeStyle=l.color;ctx.lineWidth=l.size;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();l.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();}ctx.restore();}
 if(!exporting){if(tool==='mask'){ctx.save();ctx.globalAlpha=.4;ctx.drawImage(mask,0,0);ctx.restore();}const l=layers.find(l=>l.id===selected);if(l&&l.w&&l.h){ctx.strokeStyle='#b9c7ff';ctx.lineWidth=2;ctx.strokeRect(l.x,l.y,l.w,l.h);}}}
 function layerList(){el('canvas-layers').innerHTML=[...layers].reverse().map(l=>`<button data-layer="${l.id}" class="object-row ${l.id===selected?'selected':''}">${esc(l.name||l.type)}</button>`).join('');}
 function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};}
 canvas.onpointerdown=e=>{const p=point(e);canvas.setPointerCapture(e.pointerId);if(tool==='select'){const l=[...layers].reverse().find(l=>l.w&&p.x>=l.x&&p.x<=l.x+l.w&&p.y>=l.y&&p.y<=l.y+l.h);selected=l?.id;pointer=l?{p,x:l.x,y:l.y,layer:l}:null;layerList();draw();return;}if(tool==='mask'){pointer={p,mask:true};return;}
 let layer={id:uid(),type:tool,color:el('canvas-color').value,x:p.x,y:p.y,w:1,h:1};if(['brush','eraser'].includes(tool))layer={...layer,type:'stroke',erase:tool==='eraser',size:Number(el('canvas-brush').value),points:[p]};if(tool==='text'){const text=window.prompt('Text for this layer','Your title');if(!text)return;layer={...layer,text,size:Math.max(24,Number(el('canvas-brush').value)*4),w:500,h:100};}
 layers.push(layer);selected=layer.id;pointer={p,layer};draw();layerList();};
 canvas.onpointermove=e=>{if(!pointer)return;const p=point(e);if(pointer.mask){mctx.strokeStyle='#fff';mctx.lineWidth=Number(el('canvas-brush').value);mctx.lineCap='round';mctx.beginPath();mctx.moveTo(pointer.p.x,pointer.p.y);mctx.lineTo(p.x,p.y);mctx.stroke();pointer.p=p;}else if(tool==='select'){pointer.layer.x=pointer.x+p.x-pointer.p.x;pointer.layer.y=pointer.y+p.y-pointer.p.y;}else if(pointer.layer.type==='stroke')pointer.layer.points.push(p);else if(tool!=='text'){pointer.layer.w=p.x-pointer.p.x;pointer.layer.h=p.y-pointer.p.y;}draw();};
 canvas.onpointerup=()=>{if(pointer){if(['rectangle','ellipse'].includes(pointer.layer?.type)){const l=pointer.layer;if(l.w<0){l.x+=l.w;l.w=-l.w;}if(l.h<0){l.y+=l.h;l.h=-l.h;}}pointer=null;snapshot();draw();}};
 view.querySelectorAll('[data-canvas-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.canvasTool;view.querySelectorAll('[data-canvas-tool]').forEach(n=>n.classList.toggle('selected',n===b));draw();});
 async function importImage(f){const src=await referenceData(f),image=await imageFrom(src);const scale=Math.min(canvas.width/image.width,canvas.height/image.height,1);const l={id:uid(),name:f.name||'Image',type:'image',src,x:0,y:0,w:image.width*scale,h:image.height*scale};images.set(l.id,image);layers.push(l);selected=l.id;snapshot();draw();layerList();}
 el('canvas-file').onchange=e=>{if(e.target.files[0])importImage(e.target.files[0]).catch(e=>toast(e.message));};el('canvas-layers').onclick=e=>{if(e.target.dataset.layer){selected=e.target.dataset.layer;draw();layerList();}};
 el('canvas-layer-up').onclick=()=>{const i=layers.findIndex(l=>l.id===selected);if(i>=0&&i<layers.length-1)[layers[i],layers[i+1]]=[layers[i+1],layers[i]];snapshot();draw();layerList();};el('canvas-layer-delete').onclick=()=>{layers=layers.filter(l=>l.id!==selected);selected=null;snapshot();draw();layerList();};el('canvas-undo').onclick=()=>restore(cursor-1);el('canvas-redo').onclick=()=>restore(cursor+1);
 el('canvas-size').onchange=e=>{const [w,h]=e.target.value.split(',').map(Number);canvas.width=w;canvas.height=h;mask.width=w;mask.height=h;draw();snapshot();};el('canvas-new').onclick=()=>{layers=[];selected=null;mctx.clearRect(0,0,mask.width,mask.height);snapshot();draw();layerList();};
 async function composition(){draw(true);const blob=await new Promise(r=>canvas.toBlob(r));draw();if(!blob)throw new Error('Could not export this canvas.');return blob;}
 el('canvas-export').onclick=async()=>{const blob=await composition();await put('assets',{id:uid(),name:'Canvas-'+Date.now()+'.png',type:'image',blob,created:Date.now()});await onAsset();downloadBlob(blob,'ConvertShorts-Canvas.png');};
 el('canvas-generate').onclick=async()=>{const blob=await composition();await onReference({asset:{blob,name:'Canvas composition'},prompt:'Create a polished image guided by this composition.'});};
 el('canvas-inpaint').onclick=async()=>{const blob=await composition();const base=await referenceData(blob);const maskCanvas=document.createElement('canvas');maskCanvas.width=mask.width;maskCanvas.height=mask.height;const mc=maskCanvas.getContext('2d');mc.fillStyle='#000';mc.fillRect(0,0,mask.width,mask.height);mc.drawImage(mask,0,0);await onReference({route:'ai-edit',model:'fal:fal-ai/bria/eraser',input:{image_url:base,mask_url:maskCanvas.toDataURL()},prompt:'Remove the masked region.'});};
 const saved=await get('boards','canvas-current');if(saved?.layers){layers=saved.layers;canvas.width=saved.width;canvas.height=saved.height;mask.width=saved.width;mask.height=saved.height;el('canvas-size').value=saved.width+','+saved.height;await loadImages();if(saved.mask)mctx.drawImage(await imageFrom(saved.mask),0,0);}if(asset)await importImage(asset.blob||await(await fetch(asset.remote)).blob());snapshot();draw();layerList();
 return ()=>{disposed=true;clearTimeout(timer);save().catch(e=>toast(e.message));};
}
