import {icon,escape as esc} from './icons.js';
import {uid,put,all,get,downloadBlob} from './storage.js';
export async function mountFrames(view,{toast,onAsset}){
 let videoURL='',disposed=false;const captures=[];
 view.innerHTML=`<div class="page"><div class="page-head"><div><h1>Frame Extractor</h1><p>A precise still from your video, at its original resolution. Processing stays in this browser.</p></div><label class="white-button">${icon('upload',16)} Open video<input id="frame-file" type="file" accept="video/*" hidden></label></div><div class="split-workspace"><div class="frame-preview" id="frame-stage"><div class="empty-state">${icon('frame',44)}<h2>Find that perfect frame</h2><p>Choose a local video, then scrub to any moment.</p></div></div><section class="panel"><h2>Capture controls</h2><label>Library video<select id="frame-library"><option value="">Choose a video…</option></select></label><div class="stack"><label>Position<input id="frame-scrubber" type="range" min="0" max="1" step="0.01" value="0" disabled></label><label>Time in seconds<input id="frame-time" type="number" min="0" value="0" step="0.04" disabled></label><label>Output<select id="frame-format"><option value="image/png">PNG — lossless</option><option value="image/jpeg">JPEG — smaller</option></select></label><button class="primary-button" id="capture-frame" disabled>${icon('frame',17)} Capture frame</button><div class="row"><label>Burst count<input type="number" id="burst-count" min="2" max="30" value="8"></label><label>Interval (seconds)<input type="number" id="burst-interval" min=".04" step=".1" value=".5"></label></div><button class="outline-button" id="capture-burst" disabled>Capture burst</button><button class="outline-button" id="download-frames">Download all frames (ZIP)</button><p id="video-information">No video open.</p><small>Capture at a single timestamp, or scrub and repeat. Save captures to My Library for use as AI references.</small></div></section></div><div class="section-heading"><h2>CAPTURED FRAMES</h2></div><div class="frame-list" id="captured-frames"></div></div>`;
 const el=id=>view.querySelector('#'+id);let video;
 async function openVideo(file){if(!file)return;if(videoURL)URL.revokeObjectURL(videoURL);videoURL=URL.createObjectURL(file);video=document.createElement('video');video.src=videoURL;video.controls=true;video.preload='auto';video.playsInline=true;video.muted=true;el('frame-stage').replaceChildren(video);video.addEventListener('loadedmetadata',()=>{if(disposed)return;if(!Number.isFinite(video.duration)){toast('This video format does not expose a usable timeline. Try MP4 or WebM.');return;}el('frame-scrubber').max=video.duration;el('frame-time').max=video.duration;el('frame-scrubber').disabled=false;el('frame-time').disabled=false;el('capture-frame').disabled=false;el('capture-burst').disabled=false;el('video-information').textContent=`${video.videoWidth} × ${video.videoHeight} · ${video.duration.toFixed(2)} seconds`;});video.addEventListener('timeupdate',()=>{if(disposed)return;el('frame-scrubber').value=video.currentTime;el('frame-time').value=video.currentTime.toFixed(2);});video.addEventListener('error',()=>toast('Your browser cannot decode this video. Try MP4 or WebM.'));}
 const videos=(await all('assets')).filter(a=>a.type==='video'&&!a.deleted);el('frame-library').innerHTML+=videos.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');
 el('frame-file').onchange=e=>openVideo(e.target.files[0]);el('frame-library').onchange=async e=>{const a=videos.find(a=>a.id===e.target.value);if(a)await openVideo(a.blob||await(await fetch(a.remote)).blob());};
 const seek=value=>{if(!video)return;video.pause();video.currentTime=Math.min(video.duration,Math.max(0,Number(value)));};el('frame-scrubber').oninput=e=>seek(e.target.value);el('frame-time').onchange=e=>seek(e.target.value);
 async function capture(){if(!video)return;const source=video,button=el('capture-frame');button.disabled=true;source.pause();try{if(source.readyState<2||source.seeking)await new Promise((resolve,reject)=>{const events=['seeked','loadeddata','canplay'],clear=()=>{clearTimeout(timer);events.forEach(name=>source.removeEventListener(name,check));source.removeEventListener('error',failed);},check=()=>{if(source.readyState>=2&&!source.seeking){clear();resolve();}},failed=()=>{clear();reject(new Error('This frame could not be decoded. Try another timestamp or MP4 video.'));},timer=setTimeout(failed,8000);events.forEach(name=>source.addEventListener(name,check));source.addEventListener('error',failed);check();});if(disposed||source!==video)return;const canvas=document.createElement('canvas');canvas.width=source.videoWidth;canvas.height=source.videoHeight;canvas.getContext('2d').drawImage(source,0,0);const mime=el('frame-format').value,blob=await new Promise(resolve=>canvas.toBlob(resolve,mime,.95));if(!blob)throw new Error('This frame could not be captured.');if(disposed)return;const item={id:uid(),blob,mime,name:`Frame-${source.currentTime.toFixed(2)}s.${mime==='image/png'?'png':'jpg'}`,time:source.currentTime};captures.unshift({...item,url:URL.createObjectURL(blob)});render();toast('Frame captured at full resolution.');}catch(error){if(!disposed)toast(error.message);}finally{if(!disposed&&button.isConnected)button.disabled=false;}}
 el('capture-frame').onclick=capture;
 el('capture-burst').onclick=async()=>{if(!video)return;const b=el('capture-burst');b.disabled=true;try{const start=video.currentTime,count=Math.min(30,Math.max(2,Number(el('burst-count').value)||8)),interval=Math.max(.04,Number(el('burst-interval').value)||.5);for(let i=0;i<count&&!disposed;i++){const t=start+i*interval;if(t>=video.duration)break;seek(t);await capture();}toast('Burst capture complete.');}finally{if(!disposed)b.disabled=false;}};
 el('download-frames').onclick=async()=>{if(!captures.length)return toast('Capture frames first.');const zip=new window.JSZip();captures.forEach(c=>zip.file(c.name,c.blob));downloadBlob(await zip.generateAsync({type:'blob'}),'ConvertShorts-Frames.zip');};

 function render(){el('captured-frames').innerHTML=captures.map(a=>`<div class="frame-item"><img src="${a.url}" alt="Frame at ${a.time.toFixed(2)} seconds"><small>${a.time.toFixed(2)}s</small><button class="outline-button" data-save-frame="${a.id}">Save to library</button><button class="outline-button" data-download-frame="${a.id}">Download</button></div>`).join('');}
 const handler=async e=>{const save=e.target.closest('[data-save-frame]'),download=e.target.closest('[data-download-frame]');try{if(save){const a=captures.find(a=>a.id===save.dataset.saveFrame);await put('assets',{id:a.id,blob:a.blob,name:a.name,type:'image',mime:a.mime,created:Date.now()});await onAsset();save.textContent='Saved to library';toast('Frame saved to your library.');}else if(download){const a=captures.find(a=>a.id===download.dataset.downloadFrame);downloadBlob(a.blob,a.name);}}catch(error){toast(error.message);}};view.addEventListener('click',handler);
 return ()=>{disposed=true;video?.pause();if(videoURL)URL.revokeObjectURL(videoURL);captures.forEach(c=>URL.revokeObjectURL(c.url));view.removeEventListener('click',handler);};
}
