import {icon,escape as esc} from './icons.js';
import {scopedStorage,uid,referenceData} from './storage.js';
import {uploadReference} from './cloud.js';
import {quoteDraft,formatINR} from './pricing.js';
import {schemaShape as shape,audioCapabilities,musicStyle} from './generation-controls.js';
const label=k=>({lyrics:'Lyrics',lyrics_prompt:'Lyrics',duration:'Duration (seconds)',duration_seconds:'Duration (seconds)',seconds_total:'Duration (seconds)',generate_audio:'Include generated audio',voice:'Voice'}[k]||k.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()));
const audioName=m=>m.id==='stable-audio'?'Stable Audio 2.5 · instrumentals / sounds':m.endpoint==='fal-ai/ace-step'?'ACE-Step · songs / instrumentals':m.endpoint==='fal-ai/minimax-music/v2'?'MiniMax Music · songs with lyrics':m.name;
export async function mountGenerator(view,{kind,models,ready,modeForModel=()=>ready()?'own':'connect',pricingRate=()=>null,toast,draft={},onSubmit,onDraft,renderJobs,renderResults}){
 const {all,put}=scopedStorage();
 const choices=models.filter(m=>m.kind===kind||(kind==='vfx'&&m.kind==='video'));
 const defaultModel=draft.model||(kind==='audio'?choices.find(m=>m.endpoint==='fal-ai/ace-step')?.id:undefined);
 let refs=draft.references||(draft.reference?[draft.reference]:[]),names=draft.referenceNames||[draft.referenceName||'Reference'],input=draft.input||{},guidance=draft.guidance||{vocal:'',exclude:''};
 const presets=await all('presets'),characters=await all('characters');
 view.innerHTML=`<div class="generation-page" data-kind="${kind}"><div class="page-head"><div><h1>${({image:'Create image',edit:'AI image editing',video:'Create video',audio:'Create audio',object:'Create 3D object',world:'Create 3D world',background:'Change background',vfx:'Video VFX'})[kind]}</h1><p>Choose a model, set the visible controls, and generate.</p></div><div class="head-actions"><a href="#guide" class="outline-button">How to use</a><a href="#models" class="outline-button">Model explorer</a><a href="#library" class="outline-button">Library</a></div></div><div class="generation-stage"><div id="generation-jobs"></div><div id="generation-results"></div></div><form id="generation-form" class="composer"><label class="prompt-label" for="generation-prompt" id="generation-prompt-label">Describe your idea</label><textarea id="generation-prompt" aria-label="Creation prompt" maxlength="10000" placeholder="Describe your idea, camera, lighting and style…">${esc(draft.prompt||input.tags||input.prompt||input.text||'')}</textarea><div id="reference-strip"></div><div class="composer-bottom"><label class="reference-control" id="reference-control">${icon('plus',14)} References<input id="reference-file" type="file" multiple accept="image/*"></label><select id="generation-model" aria-label="AI model">${choices.map(m=>`<option value="${esc(m.id)}" ${m.id===defaultModel?'selected':''}>${esc(kind==='audio'?audioName(m):m.name)}</option>`).join('')}</select><select id="generation-ratio" aria-label="Aspect ratio"></select><select id="generation-count" aria-label="Output count">${[1,2,3,4].map(n=>`<option value="${n}" ${Number(draft.count)===n?'selected':''}>${n} output${n>1?'s':''}</option>`).join('')}</select><button class="advanced-toggle" id="advanced-toggle" type="button" aria-expanded="false" aria-controls="advanced-controls">More settings ↓</button><button class="primary-button generate-button" id="generate">${icon('background',16)} Generate</button></div><div class="essential-controls parameter-grid" id="essential-controls"></div><p class="model-capabilities" id="model-capabilities"></p><div class="advanced-controls" id="advanced-controls" hidden><div id="model-parameters" class="parameter-grid"></div><div class="preset-row"><label>Saved prompt<select id="prompt-preset"><option value="">Choose a prompt…</option>${presets.filter(p=>!p.deleted).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><button type="button" id="save-prompt" class="outline-button">Save prompt</button><label>Character identity<select id="character-reference"><option value="">Choose a character…</option>${characters.filter(c=>!c.deleted).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label></div></div><div class="composer-hint" id="model-hint"></div></form></div>`;
 const el=id=>view.querySelector('#'+id);
 function model(){return choices.find(m=>m.id===el('generation-model').value);}
 function renderRefs(){el('reference-strip').innerHTML=refs.length?'<div class="references-row">'+refs.map((r,i)=>`<div class="reference-tile"><img src="${esc(r)}" alt="${esc(names[i]||'Reference '+(i+1))}"><span>${i+1}</span><button type="button" data-remove-ref="${i}" aria-label="Remove reference ${i+1}">×</button></div>`).join('')+'</div>':'';}
 function schemaField(k,raw){
  const s=shape(raw),required=model().schema.required?.includes(k),value=input[k]??raw.default??s.default,media=/(?:image|mask|video|audio).*url/.test(k),name=label(k)+(required?' *':'');
  const limits=`${required&&s.type!=='boolean'&&!media?'required':''} ${s.minLength!==undefined?`minlength="${s.minLength}"`:''} ${s.maxLength!==undefined?`maxlength="${s.maxLength}"`:''}`;let control;
  if(s.enum)control=`<select data-param="${k}" ${limits}>${!required&&value===undefined?'<option value="">Model default</option>':''}${s.enum.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(k==='duration'?String(v).replace(/s$/,'')+' seconds':v)}</option>`).join('')}</select>`;
  else if(s.type==='boolean')control=`<input type="checkbox" data-param="${k}" ${value===true?'checked':''}>`;
  else if(['integer','number'].includes(s.type))control=`<input type="number" data-param="${k}" ${s.minimum!==undefined?`min="${s.minimum}"`:''} ${s.maximum!==undefined?`max="${s.maximum}"`:''} step="${s.type==='integer'?'1':'any'}" value="${value??''}" ${limits} placeholder="Model default">`;
  else if(s.type==='object'||s.properties||s.type==='array')control=`<textarea rows="2" data-param="${k}" data-json="true" ${limits} placeholder="${media?'Reference images above are used automatically':'JSON value'}">${value===undefined?'':esc(JSON.stringify(value))}</textarea>`;
  else if((s.maxLength||0)>300||k.includes('lyrics'))control=`<textarea rows="${k.includes('lyrics')?5:3}" data-param="${k}" ${limits} placeholder="${k.includes('lyrics')?'[Verse]\nYour lyrics here\n\n[Chorus]\nYour chorus here':'Model default'}">${esc(value??'')}</textarea>`;
  else control=`<input data-param="${k}" value="${esc(value??'')}" ${limits} placeholder="${media?'HTTPS URL, or upload below':'Model default'}">`;
  return `<label class="model-field ${k.includes('lyrics')?'lyrics-field':''} ${media?'media-field':''}" title="${esc((raw.description||s.description||'').slice(0,350))}">${name}${control}${media?`<input type="file" data-media="${k}" accept="${k.includes('video')?'video/*':k.includes('audio')?'audio/*':'image/*'}" ${s.type==='array'?'multiple':''}>`:''}<small>${esc((raw.description||s.description||'').slice(0,k.includes('lyrics')?250:140))}</small></label>`;
 }
 function renderParameters(){
  const m=model();if(!m)return;const schema=m.schema,properties=schema?.properties||{},caps=m.kind==='audio'?audioCapabilities(m):{},primaryKey=caps.styleKey||(properties.text?'text':'prompt');
  const oldRatio=el('generation-ratio').value||draft.ratio,ratios=shape(properties.aspect_ratio||{}).enum||(!schema&&['image','edit','video'].includes(m.kind)?['1:1','16:9','9:16','3:2','2:3','4:3','3:4']:[]);
  el('generation-ratio').hidden=!ratios.length;el('generation-ratio').innerHTML=ratios.map(r=>`<option ${r===oldRatio?'selected':''}>${r}</option>`).join('');
  const ps=shape(properties[primaryKey]||{});el('generation-prompt').maxLength=m.endpoint==='fal-ai/minimax-music/v2'?300:ps.maxLength||10000;el('generation-prompt').minLength=ps.minLength||0;
  el('generation-prompt').required=!!schema?.required?.includes(primaryKey)||!schema&&!['object','world','background'].includes(m.kind);
  el('generation-prompt-label').textContent=caps.speech?'Speech text':m.kind==='audio'?'Music style / audio description':'Describe your idea';
  el('generation-prompt').placeholder=caps.speech?'Enter the words to speak…':m.kind==='audio'?'Describe the genre, mood, instruments, tempo and language…':'Describe your idea, camera, lighting and style…';
  el('generation-count').hidden=!['image','edit'].includes(m.kind);el('reference-control').hidden=!m.reference;
  el('model-capabilities').textContent=m.kind==='audio'?caps.description:m.kind==='video'?'Duration uses the selected model’s supported lengths. Image-to-video needs a reference image; text-to-video uses your prompt.':m.kind==='object'?'Upload an image of one object, generate, then open the result in Edit 3D.':m.kind==='world'?'Upload a scene image and set the required scene controls. Explore supported world files in Explore Worlds.':'';
  if(!schema){
   el('essential-controls').innerHTML=`${['image','edit','object'].includes(m.kind)?`<label>Resolution<select id="generation-resolution">${(m.kind==='object'?['512','1024','1536']:['1K','2K','4K']).map(v=>`<option ${v===draft.resolution?'selected':''}>${v}</option>`).join('')}</select></label>`:''}${['audio','video'].includes(m.kind)?`<label>Duration (seconds)<select id="generation-duration">${(m.kind==='video'?[5,10]:[10,30,60,120,190]).map(n=>`<option value="${n}" ${Number(draft.duration)===n?'selected':''}>${n} seconds</option>`).join('')}</select></label>`:''}${m.kind==='video'?`<label><input id="generation-audio" type="checkbox" ${draft.audio?'checked':''}> Include generated audio</label>`:''}`;
   el('model-parameters').innerHTML=`${['image','edit'].includes(m.kind)?`<label>Seed<input id="generation-seed" type="number" min="0" max="2147483647" value="${esc(draft.seed||'')}" placeholder="Random"></label>`:''}${m.kind==='video'?`<label>Negative prompt<input id="generation-negative" value="${esc(draft.negative||'')}"></label>`:''}${m.kind==='world'?'<label>Foreground 1<input id="labels_fg1" value="tree, grass, sky"></label><label>Foreground 2<input id="labels_fg2" value="mountain, water"></label><label>Classes<input id="classes" value="nature, landscape"></label>':''}`;
  }else{
   const primary=['prompt','text','num_images','aspect_ratio',...(caps.styleKey==='tags'?['tags']:[])],essential=['duration','duration_seconds','seconds_total','resolution','generate_audio','audio','lyrics','lyrics_prompt','voice','speed',...(schema.required||[])];
   const fields=Object.entries(properties).filter(([k])=>!primary.includes(k)&&!['enable_safety_checker','sync_mode','safety_tolerance'].includes(k));
   el('essential-controls').innerHTML=fields.filter(([k])=>essential.includes(k)).map(([k,s])=>schemaField(k,s)).join('');
   el('model-parameters').innerHTML=fields.filter(([k])=>!essential.includes(k)).map(([k,s])=>schemaField(k,s)).join('');
  }
  if(caps.song)el('essential-controls').insertAdjacentHTML('beforeend',`<label>Vocal preference<select id="music-vocals"><option value="">Model default</option><option value="female" ${guidance.vocal==='female'?'selected':''}>Female singer</option><option value="male" ${guidance.vocal==='male'?'selected':''}>Male singer</option><option value="duet" ${guidance.vocal==='duet'?'selected':''}>Male / female duet</option>${caps.instrumental?`<option value="instrumental" ${guidance.vocal==='instrumental'?'selected':''}>Instrumental · no vocals</option>`:''}</select></label><label>Exclude styles<input id="music-excludes" maxlength="180" value="${esc(guidance.exclude||'')}" placeholder="e.g. phonk, heavy bass, high-pitched vocals"></label><p class="guidance-note">Vocal preference and exclusions are added to the music description as guidance. This model does not guarantee a particular singer or enforce excluded styles.</p>`);
  updatePrice();
 }
 function parameterInput(){
  const m=model(),properties=m.schema?.properties||{},out={};
  for(const n of view.querySelectorAll('[data-param]')){const k=n.dataset.param,s=shape(properties[k]);if(n.type==='checkbox'){out[k]=n.checked;continue;}if(n.value==='')continue;out[k]=n.dataset.json?JSON.parse(n.value):['number','integer'].includes(s.type)?Number(n.value):n.value;}
  const caps=m.kind==='audio'?audioCapabilities(m):{},key=caps.styleKey||(properties.text?'text':'prompt');
  if(properties[key])out[key]=caps.song?musicStyle(el('generation-prompt').value,{vocal:el('music-vocals').value,exclude:el('music-excludes').value},el('generation-prompt').maxLength):el('generation-prompt').value;
  if(caps.instrumental&&el('music-vocals').value==='instrumental')out[caps.lyricsKey]='[instrumental]';
  if(properties.num_images)out.num_images=Number(el('generation-count').value);
  if(properties.aspect_ratio)out.aspect_ratio=el('generation-ratio').value;
  if(refs.length){if(properties.image_urls&&!out.image_urls)out.image_urls=refs;if(properties.reference_image_urls&&!out.reference_image_urls)out.reference_image_urls=refs;for(const k of ['image_url','input_image_url','start_image_url','front_image_url'])if(properties[k]&&!out[k])out[k]=refs[0];for(const k of ['end_image_url','tail_image_url'])if(properties[k]&&!out[k]&&refs[1])out[k]=refs[1];}
  return out;
 }
 function state(){return {prompt:el('generation-prompt').value,model:model().id,ratio:el('generation-ratio').value,references:refs,referenceNames:names,count:el('generation-count').value,resolution:el('generation-resolution')?.value,duration:el('generation-duration')?.value,seed:el('generation-seed')?.value,negative:el('generation-negative')?.value,audio:!!el('generation-audio')?.checked,labels_fg1:el('labels_fg1')?.value,labels_fg2:el('labels_fg2')?.value,classes:el('classes')?.value,input:model().schema?parameterInput():{},guidance:{vocal:el('music-vocals')?.value||'',exclude:el('music-excludes')?.value||''}};}
 function updatePrice(){const m=model();if(!m)return;const mode=modeForModel(m);let text=mode==='own'?'Your provider account is billed when you submit. ':mode==='signin'?'Sign in to generate with ConvertShorts credits. ':m.provider==='worldlabs'?'Connect your World Labs key in Settings. ':'Connect your Fal key in Settings to generate. ';let suffix='';
  if(mode==='hosted'||mode==='signin')try{const q=quoteDraft(m,{...state(),reference:refs[0]},pricingRate());if(!q.credits)throw Error('A current INR price is unavailable.');text=formatINR(q.retailInr)+' for this request · Fal cost + 20%. '+(mode==='signin'?'Sign in to use your prepaid balance. ':'');suffix=' · '+formatINR(q.retailInr);}catch(e){text=e.message+' ';}
  el('model-hint').innerHTML=esc(text)+(mode==='signin'?'<a href="#account">Sign in</a> · ':'')+'<a href="#billing">Pricing & credits</a> · '+`<a href="${m.provider==='worldlabs'?'https://docs.worldlabs.ai/api':'https://fal.ai/models/'+esc(m.endpoint)}" target="_blank" rel="noopener">Model documentation & current pricing ↗</a>`;
  const b=el('generate');if(!b.disabled)b.innerHTML=icon('background',16)+' Generate'+suffix;
 }
 el('generation-form').addEventListener('input',updatePrice);el('generation-form').addEventListener('change',updatePrice);
 el('generation-model').onchange=()=>{guidance={vocal:el('music-vocals')?.value||'',exclude:el('music-excludes')?.value||''};const prior={};for(const n of view.querySelectorAll('[data-param]'))if(n.value!=='')prior[n.dataset.param]=n.type==='checkbox'?n.checked:n.dataset.json?undefined:n.value;const p=model().schema?.properties||{};input={};for(const [k,raw] of Object.entries(p)){const s=shape(raw),v=prior[k]??(k==='lyrics_prompt'?prior.lyrics:k==='lyrics'?prior.lyrics_prompt:undefined);if(v===undefined||s.enum&&!s.enum.includes(v))continue;const value=['number','integer'].includes(s.type)?Number(v):v;if(typeof value==='number'&&(s.minimum!==undefined&&value<s.minimum||s.maximum!==undefined&&value>s.maximum))continue;input[k]=value;}draft={};renderParameters();};
 el('advanced-toggle').onclick=()=>{el('advanced-controls').hidden=!el('advanced-controls').hidden;el('advanced-toggle').setAttribute('aria-expanded',String(!el('advanced-controls').hidden));};
 el('reference-strip').onclick=e=>{const index=e.target.dataset.removeRef;if(index!==undefined){refs.splice(Number(index),1);names.splice(Number(index),1);renderRefs();updatePrice();}};
 el('reference-file').onchange=async e=>{try{for(const f of [...e.target.files].slice(0,(kind==='video'?30:6)-refs.length)){refs.push(await referenceData(f));names.push(f.name);}renderRefs();updatePrice();}catch(e){toast(e.message);}};
 el('generation-form').addEventListener('change',async e=>{const key=e.target.dataset.media;if(!key)return;try{const n=view.querySelector('[data-param="'+key+'"]'),s=shape(model().schema.properties[key]),values=[];for(const file of e.target.files){values.push(file.type.startsWith('image/')?await referenceData(file):await uploadReference(file));}n.value=s.type==='array'?JSON.stringify(values):values[0];toast('Media reference ready.');}catch(e){toast(e.message);}});
 el('prompt-preset').onchange=e=>{const p=presets.find(p=>p.id===e.target.value);if(p)el('generation-prompt').value=p.prompt;};
 el('save-prompt').onclick=async()=>{const prompt=el('generation-prompt').value.trim();if(!prompt)return toast('Write a prompt first.');await put('presets',{id:uid(),name:prompt.slice(0,60),prompt,model:model().id,created:Date.now()});toast('Prompt saved in your workspace.');};
 el('character-reference').onchange=e=>{const c=characters.find(c=>c.id===e.target.value);if(!c)return;el('generation-prompt').value=[c.description,el('generation-prompt').value].filter(Boolean).join('\n');for(const ref of c.references||[])if(refs.length<6){refs.push(ref);names.push(c.name);}renderRefs();};
 el('generation-form').onsubmit=async e=>{e.preventDefault();const m=model();if(!m)return toast('Choose a model.');const b=el('generate');b.disabled=true;b.textContent='Submitting…';
  try{if(refs.reduce((n,r)=>n+r.length,0)>2800000){for(let i=0;i<refs.length;i++)if(refs[i].startsWith('data:'))refs[i]=await uploadReference(await(await fetch(refs[i])).blob());renderRefs();}if(refs.length&&!m.reference)throw Error('Choose a model that supports image references.');const s=state();onDraft(s);const body={...s,reference:refs[0]};delete body.guidance;if(!m.schema)delete body.input;await onSubmit(body,m);}
  catch(e){toast(e.message);}finally{if(b.isConnected){b.disabled=false;updatePrice();}}
 };
 renderRefs();renderParameters();renderJobs();renderResults(kind);
 if(['world','object','edit','vfx'].includes(kind)){el('advanced-controls').hidden=false;el('advanced-toggle').setAttribute('aria-expanded','true');}
 return ()=>{try{onDraft(state());}catch{}};
}
