import {icon,escape as esc} from './icons.js';
import {scopedStorage,all,put,uid,referenceData} from './storage.js';
import {uploadReference} from './cloud.js';
function shape(s){return s.anyOf?.find(v=>v.type!=='null')||s.oneOf?.find(v=>v.type!=='null')||s;}
const label=k=>k.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export async function mountGenerator(view,{kind,models,ready,toast,draft={},onSubmit,onDraft,renderJobs,renderResults}){
 const {all,get,put}=scopedStorage();
 const choices=models.filter(m=>m.kind===kind||(kind==='vfx'&&m.kind==='video'));
 let refs=draft.references|| (draft.reference?[draft.reference]:[]),names=draft.referenceNames||[draft.referenceName||'Reference'],input=draft.input||{};
 const presets=await all('presets'),characters=await all('characters');
 view.innerHTML=`<div class="generation-page"><div class="page-head"><div><h1>${({image:'Create image',edit:'AI image editing',video:'Create video',audio:'Create audio',object:'Create 3D object',world:'Create 3D world',background:'Change background',vfx:'Video VFX'})[kind]}</h1><p>Choose a model, bring references, and refine your result.</p></div><div class="head-actions"><a href="#models" class="outline-button">Model explorer</a><a href="#library" class="outline-button">Library</a></div></div><div class="generation-stage"><div id="generation-jobs"></div><div id="generation-results"></div></div><form id="generation-form" class="composer"><textarea id="generation-prompt" aria-label="Creation prompt" maxlength="10000" placeholder="Describe your idea, camera, lighting and style…">${esc(draft.prompt||'')}</textarea><div id="reference-strip"></div><div class="composer-bottom"><label class="reference-control">${icon('plus',14)} References<input id="reference-file" type="file" multiple accept="image/*"></label><select id="generation-model" aria-label="AI model">${choices.map(m=>`<option value="${esc(m.id)}" ${m.id===draft.model?'selected':''}>${esc(m.name)}</option>`).join('')}</select><select id="generation-ratio" aria-label="Aspect ratio">${['1:1','16:9','9:16','3:2','2:3','4:3','3:4','4:5','5:4','21:9','auto'].map(r=>`<option ${r===draft.ratio?'selected':''}>${r}</option>`).join('')}</select><select id="generation-count" aria-label="Output count"><option value="1">1 output</option><option value="2">2 outputs</option><option value="3">3 outputs</option><option value="4">4 outputs</option></select><button class="advanced-toggle" id="advanced-toggle" type="button">Options ↓</button><button class="primary-button generate-button" id="generate">${icon('background',16)} Generate</button></div><div class="advanced-controls" id="advanced-controls" hidden><div id="model-parameters" class="parameter-grid"></div><div class="preset-row"><label>Saved prompt<select id="prompt-preset"><option value="">Choose a prompt…</option>${presets.filter(p=>!p.deleted).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><button type="button" id="save-prompt" class="outline-button">Save prompt</button><label>Character identity<select id="character-reference"><option value="">Choose a character…</option>${characters.filter(c=>!c.deleted).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label></div></div><div class="composer-hint" id="model-hint"></div></form></div>`;
 const el=id=>view.querySelector('#'+id);
 function model(){return choices.find(m=>m.id===el('generation-model').value);}
 function renderRefs(){el('reference-strip').innerHTML=refs.length?'<div class="references-row">'+refs.map((r,i)=>`<div class="reference-tile"><img src="${esc(r)}" alt="${esc(names[i]||'Reference '+(i+1))}"><span>${i+1}</span><button type="button" data-remove-ref="${i}" aria-label="Remove reference ${i+1}">×</button></div>`).join('')+'</div>':'';el('reference-strip').onclick=e=>{const index=e.target.dataset.removeRef;if(index!==undefined){refs.splice(Number(index),1);names.splice(Number(index),1);renderRefs();}};}
 function renderParameters(){const m=model();if(!m)return;const schema=m.schema;const properties=schema?.properties||{};const oldRatio=el('generation-ratio').value,ratios=shape(properties.aspect_ratio||{}).enum||(schema?[]:['1:1','16:9','9:16','3:2','2:3','4:3','3:4']);el('generation-ratio').hidden=!ratios.length;el('generation-ratio').innerHTML=ratios.map(r=>`<option ${r===oldRatio?'selected':''}>${r}</option>`).join('');el('generation-prompt').maxLength=shape(properties.prompt||properties.text||{}).maxLength||10000;
 el('model-hint').innerHTML=(ready()?m.credits?'Workspace generation costs '+m.credits+' credits when using the hosted service. Your own key uses provider billing. ':'Your connected provider account is billed when you submit. ':'Connect AI in Settings to generate. ')+`<a href="${m.provider==='worldlabs'?'https://docs.worldlabs.ai/api':'https://fal.ai/models/'+esc(m.endpoint)}" target="_blank" rel="noopener">Model documentation & current pricing ↗</a>`;
 el('generation-count').hidden=!['image','edit'].includes(kind);
 if(!schema){el('model-parameters').innerHTML=`${['image','edit'].includes(kind)?'<label>Seed<input id="generation-seed" type="number" min="0" max="2147483647" placeholder="Random"></label>':''}${['image','edit','object'].includes(kind)?`<label>Resolution<select id="generation-resolution">${(kind==='object'?['512','1024','1536']:['1K','2K','4K']).map(v=>`<option>${v}</option>`).join('')}</select></label>`:''}${['audio','video'].includes(kind)?`<label>Duration<select id="generation-duration">${(kind==='video'?[5,10]:[10,30,60,120,190]).map(n=>`<option value="${n}">${n} seconds</option>`).join('')}</select></label>`:''}${kind==='video'?'<label>Negative prompt<input id="generation-negative"></label><label><input id="generation-audio" type="checkbox"> Native audio</label>':''}${kind==='world'?'<label>Foreground 1<input id="labels_fg1" value="tree, grass, sky"></label><label>Foreground 2<input id="labels_fg2" value="mountain, water"></label><label>Classes<input id="classes" value="nature, landscape"></label>':''}`;return;}
 const primary=['prompt','text','num_images','aspect_ratio'];
 el('model-parameters').innerHTML=Object.entries(properties).filter(([k])=>!primary.includes(k)&&!['enable_safety_checker','sync_mode','safety_tolerance'].includes(k)).map(([k,raw])=>{const s=shape(raw),required=schema.required?.includes(k),value=input[k]??s.default,media=/(?:image|mask|video|audio).*url/.test(k),name=label(k)+(required?' *':'');let control;
 if(s.enum)control=`<select data-param="${k}">${!required&&value===undefined?'<option value="">Model default</option>':''}${s.enum.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`;
 else if(s.type==='boolean')control=`<input type="checkbox" data-param="${k}" ${value===true?'checked':''}>`;
 else if(['integer','number'].includes(s.type))control=`<input type="number" data-param="${k}" ${s.minimum!==undefined?`min="${s.minimum}"`:''} ${s.maximum!==undefined?`max="${s.maximum}"`:''} step="${s.type==='integer'?'1':'any'}" value="${value??''}" placeholder="Model default">`;
 else if(s.type==='object'||s.properties||s.type==='array')control=`<textarea rows="2" data-param="${k}" data-json="true" placeholder="${media?'Reference images above are used automatically':'JSON value'}">${value===undefined?'':esc(JSON.stringify(value))}</textarea>`;
 else if((s.maxLength||0)>300||k.includes('lyrics'))control=`<textarea rows="3" data-param="${k}" maxlength="${s.maxLength||10000}" placeholder="Model default">${esc(value??'')}</textarea>`;
 else control=`<input data-param="${k}" value="${esc(value??'')}" placeholder="${media?'HTTPS URL, or upload below':'Model default'}" maxlength="10000">`;
 return `<label class="model-field ${media?'media-field':''}" title="${esc((s.description||'').slice(0,350))}">${name}${control}${media?`<input type="file" data-media="${k}" accept="${k.includes('video')?'video/*':k.includes('audio')?'audio/*':'image/*'}" ${s.type==='array'?'multiple':''}>`:''}<small>${esc((s.description||'').slice(0,110))}</small></label>`;}).join('');
 }
 function parameterInput(){const m=model(),properties=m.schema?.properties||{},out={};for(const n of view.querySelectorAll('[data-param]')){const k=n.dataset.param,s=shape(properties[k]);if(n.type==='checkbox'){out[k]=n.checked;continue;}if(n.value==='')continue;out[k]=n.dataset.json?JSON.parse(n.value):['number','integer'].includes(s.type)?Number(n.value):n.value;}
 if(properties.prompt)out.prompt=el('generation-prompt').value;
 if(properties.text)out.text=el('generation-prompt').value;
 if(properties.num_images)out.num_images=Number(el('generation-count').value);
 if(properties.aspect_ratio)out.aspect_ratio=el('generation-ratio').value;
 if(refs.length){if(properties.image_urls&&!out.image_urls)out.image_urls=refs;if(properties.image_url&&!out.image_url)out.image_url=refs[0];if(properties.start_image_url&&!out.start_image_url)out.start_image_url=refs[0];if(properties.end_image_url&&!out.end_image_url&&refs[1])out.end_image_url=refs[1];if(properties.front_image_url&&!out.front_image_url)out.front_image_url=refs[0];}
 return out;
 }
 el('generation-model').onchange=()=>{input={};renderParameters();};el('advanced-toggle').onclick=()=>el('advanced-controls').hidden=!el('advanced-controls').hidden;
 el('reference-file').onchange=async e=>{try{for(const f of [...e.target.files].slice(0,(kind==='video'?30:6)-refs.length)){refs.push(await referenceData(f));names.push(f.name);}renderRefs();}catch(e){toast(e.message);}};
 el('model-parameters').onchange=async e=>{const key=e.target.dataset.media;if(!key)return;try{const n=view.querySelector('[data-param="'+key+'"]'),s=shape(model().schema.properties[key]),values=[];for(const file of e.target.files){values.push(file.type.startsWith('image/')?await referenceData(file):await uploadReference(file));}n.value=s.type==='array'?JSON.stringify(values):values[0];toast('Media reference ready.');}catch(e){toast(e.message);}};
 el('prompt-preset').onchange=e=>{const p=presets.find(p=>p.id===e.target.value);if(p)el('generation-prompt').value=p.prompt;};
 el('save-prompt').onclick=async()=>{const prompt=el('generation-prompt').value.trim();if(!prompt)return toast('Write a prompt first.');await put('presets',{id:uid(),name:prompt.slice(0,60),prompt,model:model().id,created:Date.now()});toast('Prompt saved in your workspace.');};
 el('character-reference').onchange=async e=>{const c=characters.find(c=>c.id===e.target.value);if(!c)return;el('generation-prompt').value=[c.description,el('generation-prompt').value].filter(Boolean).join('\n');for(const ref of c.references||[])if(refs.length<6){refs.push(ref);names.push(c.name);}renderRefs();};
 el('generation-form').onsubmit=async e=>{e.preventDefault();const m=model();if(!m)return toast('Choose a model.');const b=el('generate');b.disabled=true;b.textContent='Submitting…';const prompt=el('generation-prompt').value;
 try{if(refs.reduce((n,r)=>n+r.length,0)>2800000){for(let i=0;i<refs.length;i++)if(refs[i].startsWith('data:'))refs[i]=await uploadReference(await(await fetch(refs[i])).blob());renderRefs();}if(refs.length&&!m.reference)throw new Error('Choose a model that supports image references.');const state={prompt,model:m.id,ratio:el('generation-ratio').value,references:refs,referenceNames:names,input:m.schema?parameterInput():{}};onDraft(state);let body={model:m.id,prompt,ratio:state.ratio,count:el('generation-count').value,reference:refs[0],references:refs,resolution:el('generation-resolution')?.value,duration:el('generation-duration')?.value,seed:el('generation-seed')?.value,negative:el('generation-negative')?.value,audio:!!el('generation-audio')?.checked,labels_fg1:el('labels_fg1')?.value,labels_fg2:el('labels_fg2')?.value,classes:el('classes')?.value};if(m.schema)body.input=state.input;await onSubmit(body,m);}
 catch(e){toast(e.message);}finally{if(b.isConnected){b.disabled=false;b.innerHTML=icon('background',16)+' Generate';}};
 };
 renderRefs();renderParameters();renderJobs();renderResults(kind);
 if(['world','object','edit','vfx'].includes(kind))el('advanced-controls').hidden=false;
 return ()=>{try{onDraft({prompt:el('generation-prompt')?.value,model:el('generation-model')?.value,ratio:el('generation-ratio')?.value,references:refs,referenceNames:names,input:model()?.schema?parameterInput():{}});}catch{}};
}
