import {MODEL_PRICE_CATALOG,PRICE_REVIEW_DATE} from './price-catalog.js';
import {formatINR,formatUSD,formatCredits,retailFromProvider,supportsHostedPricing} from './pricing.js';
import {escape as esc} from './icons.js';

const statuses={reviewed:'Rate reviewed',metered:'Usage metering needed',tentative:'Tentative provider rate',conflicting:'Provider rate needs confirmation',unverified:'Price unverified'};
function rows(rate){return MODEL_PRICE_CATALOG.map(m=>{
  const usd=m.rates.map(r=>`<li>${esc(r.label)}: ${formatUSD(retailFromProvider(r.providerUsd))} / ${esc(r.unit)}</li>`).join('');
  const credits=rate?m.rates.map(r=>`<li>${esc(r.label)}: ${formatCredits(Math.ceil(retailFromProvider(r.providerUsd)*rate*100-1e-9)/100)} / ${esc(r.unit)}</li>`).join(''):'<li>Current INR conversion unavailable</li>';
  return `<tr data-price-kind="${esc(m.kind)}" data-price-search="${esc((m.name+' '+m.endpoint+' '+m.note).toLowerCase())}"><th scope="row"><a href="${esc(m.source)}" target="_blank" rel="noopener noreferrer">${esc(m.name)} ↗</a><small>${esc(m.endpoint)}</small><span class="price-status">${supportsHostedPricing(m)?'Initial launch · coming soon':'Pricing preview · coming soon'}</span><small>${esc(statuses[m.status])}</small>${m.note?`<p>${esc(m.note)}</p>`:''}</th><td><ul>${m.rates.map(r=>`<li>${esc(r.label)}: ${formatUSD(r.providerUsd)} / ${esc(r.unit)}</li>`).join('')||'<li>Not verified</li>'}</ul></td><td><ul>${usd||'<li>Unavailable</li>'}</ul></td><td><ul>${m.rates.length?credits:'<li>Unavailable</li>'}</ul></td></tr>`;
}).join('');}

export function priceCatalogSection({usdInr=null,fxDate=''}={}){
  return `<section class="fal-price-catalog" id="fal-prices"><div class="price-catalog-intro"><span class="eyebrow">MODEL PRICES · REVIEWED ${PRICE_REVIEW_DATE}</span><h2>Provider rates, with 20% added.</h2><p>74 Fal endpoints in our studio catalog. Every priced unit below uses the same formula: <strong>Fal rate × 1.20</strong>. These are reference rates, not complete job quotes. Multiply by the actual billable seconds, images, pixels or tokens, and include every add-on. Only the initial launch models have exact paid-request pricing; all AI generation is coming soon.</p><p class="price-fx-note">${usdInr?`$1 = ${formatINR(usdInr)} · ${esc(fxDate)} · daily reference conversion.`:'USD rates are shown below. Current rupee / credit equivalents will appear when a current conversion rate is available.'} 1 ConvertShorts credit = ₹1. Fractional credits are supported. Unit credit equivalents are rounded separately for illustration; complete requests are rounded once after the total.</p></div><div class="price-catalog-filters"><label>Find a model<input type="search" data-price-search-input placeholder="Seedance, Kling, music…" autocomplete="off"></label><label>Type<select data-price-kind-input><option value="all">All models</option>${[['image','Image'],['edit','Image editing'],['video','Video'],['audio','Audio'],['object','3D objects'],['world','3D worlds'],['background','Background']].map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><p data-price-count aria-live="polite">74 endpoints shown</p></div><div class="table-scroll"><table class="model-rate-table"><caption>Fal rates and ConvertShorts reference rates. Prices do not mean a model is available for purchase.</caption><thead><tr><th>Model / status</th><th>Fal rate (USD)</th><th>Our rate (USD + 20%)</th><th>Credits per unit</th></tr></thead><tbody>${rows(usdInr)}</tbody></table></div><p>No discounts, output counts or promotional rates are guaranteed. Actual Fal invoices still need reconciliation before launch. Confirmed failed requests return reserved balance; any provider charges on failed requests are our operating cost.</p><div class="credit-example"><h3>See how your credits work</h3><p>This calculator illustrates the markup using an assumed provider cost in rupees. It does not quote a model or submit a generation.</p><div class="price-catalog-filters"><label>Provider cost (₹)<input data-example-cost type="number" min="0" max="1000000" step="0.01" value="200"></label><label>Your starting credits<input data-example-balance type="number" min="0" max="1000000" step="0.01" value="1000"></label></div><p data-example-result aria-live="polite">₹200 provider cost + ₹40 markup = <strong>240 credits (₹240)</strong>. Starting with 1,000 credits leaves <strong>760 credits (₹760)</strong>. Markup is before operating expenses.</p></div></section>`;
}

export function mountPriceCatalog(section){
  const search=section.querySelector('[data-price-search-input]'),kind=section.querySelector('[data-price-kind-input]');
  function filter(){const q=search.value.trim().toLowerCase();let count=0;for(const row of section.querySelectorAll('tbody tr')){row.hidden=!(kind.value==='all'||row.dataset.priceKind===kind.value)||!row.dataset.priceSearch.includes(q);if(!row.hidden)count++;}section.querySelector('[data-price-count]').textContent=count+' endpoint'+(count===1?'':'s')+' shown';}
  search.addEventListener('input',filter);kind.addEventListener('change',filter);
  const cost=section.querySelector('[data-example-cost]'),balance=section.querySelector('[data-example-balance]'),result=section.querySelector('[data-example-result]');
  function example(){if(!cost.value||!balance.value||!cost.validity.valid||!balance.validity.valid){result.textContent='Enter valid non-negative amounts.';return;}const provider=Number(cost.value),starting=Number(balance.value),price=Math.ceil(retailFromProvider(provider)*100-1e-9)/100,remaining=Math.round((starting-price)*100)/100;result.textContent=formatINR(provider)+' provider cost + '+formatINR(Math.round(provider*.2*100)/100)+' markup = '+formatCredits(price)+' ('+formatINR(price)+'). '+(remaining<0?'Insufficient balance. Add '+formatCredits(-remaining)+' to generate.':'Remaining: '+formatCredits(remaining)+' ('+formatINR(remaining)+').')+' Markup is before operating expenses.';}
  cost.addEventListener('input',example);balance.addEventListener('input',example);
}
