import {scopedStorage,all,get,put,uid,referenceData,downloadBlob} from './storage.js';
import {escape as esc,icon} from './icons.js';
export async function mountProjects(view,{toast,assetURL,onReference}){
 const {all,get,put}=scopedStorage();
 let projects=(await all('projects')).filter(p=>!p.deleted),active=projects.find(p=>p.id===localStorage.getItem('convertshorts-current-project'))||projects[0];
 const assets=(await all('assets')).filter(a=>!a.deleted);let timer;
 async function save(){if(!active)return;await put('projects',active);toast('Project saved.');}
 function render(){view.innerHTML=`<div class="page"><div class="page-head"><div><h1>Projects & shot lists</h1><p>Plan a story, link references, and hand off each shot to generation.</p></div><div class="head-actions"><button class="white-button" id="new-project">+ New project</button></div></div><div class="project-layout"><aside class="panel"><h2>Projects</h2>${projects.map(p=>`<button class="project-link ${p===active?'selected':''}" data-project="${p.id}">${esc(p.name)}<small>${p.shots?.length||0} shots</small></button>`).join('')||'<p>Create a project to start planning.</p>'}</aside><section class="panel">${active?`<div class="row"><input id="project-name" aria-label="Project name" value="${esc(active.name)}" maxlength="80"><button id="export-project" class="outline-button">Export JSON</button><button id="archive-project" class="outline-button">Archive</button></div><label>Creative brief<textarea id="project-brief" rows="3" placeholder="Mood, audience, setting, characters…">${esc(active.brief||'')}</textarea></label><div class="row"><button id="add-shot" class="primary-button">+ Add shot</button><button id="save-project" class="outline-button">Save project</button></div><div class="shot-list">${(active.shots||[]).map((s,i)=>`<article class="shot-card" data-shot="${s.id}"><div class="shot-number">${String(i+1).padStart(2,'0')}</div><div><input data-shot-title="${s.id}" value="${esc(s.title)}" aria-label="Shot ${i+1} title"><textarea data-shot-prompt="${s.id}" placeholder="Describe action, camera, lighting…">${esc(s.prompt||'')}</textarea><div class="row"><label>Duration<input data-shot-duration="${s.id}" type="number" min="1" max="120" value="${s.duration||5}"></label><label>Reference<select data-shot-asset="${s.id}"><option value="">Choose an image…</option>${assets.filter(a=>a.type==='image').map(a=>`<option value="${a.id}" ${a.id===s.asset?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label>Status<select data-shot-status="${s.id}">${['Planned','Generating','Review','Approved'].map(t=>`<option ${s.status===t?'selected':''}>${t}</option>`).join('')}</select></label></div><div class="row"><button data-generate-shot="${s.id}" class="outline-button">Generate image</button><button data-video-shot="${s.id}" class="outline-button">Generate video</button><button data-move-shot="${s.id}" class="outline-button">↑ Move earlier</button><button data-delete-shot="${s.id}" class="outline-button">Remove</button></div></div>${s.asset?`<img class="shot-reference" src="${esc(assetURL(assets.find(a=>a.id===s.asset)||{} )||'')}" alt="Shot reference">`:''}</article>`).join('')}</div>`:'<p>Keep your story and references in one place.</p>'}</section></div></div>`;
 const el=id=>view.querySelector('#'+id);el('new-project').onclick=async()=>{if(active)await save();active={id:uid(),name:'Untitled project',brief:'',shots:[],created:Date.now()};projects.unshift(active);localStorage.setItem('convertshorts-current-project',active.id);await put('projects',active);render();};
 if(!active)return;
 el('project-name').oninput=e=>{active.name=e.target.value;schedule();};el('project-brief').oninput=e=>{active.brief=e.target.value;schedule();};el('save-project').onclick=async()=>{const b=el('save-project');b.disabled=true;try{await save();}finally{if(b.isConnected)b.disabled=false;}};
 el('add-shot').onclick=async()=>{active.shots.push({id:uid(),title:'Shot '+(active.shots.length+1),prompt:'',duration:5,status:'Planned'});await save();render();};
 el('export-project').onclick=()=>downloadBlob(new Blob([JSON.stringify({format:'convertshorts-story-v1',...active},null,2)],{type:'application/json'}),active.name.replace(/[^\w-]/g,'-')+'.json');
 el('archive-project').onclick=async()=>{active.deleted=true;await save();projects=projects.filter(p=>p!==active);active=projects[0];render();};
 }
 function schedule(){clearTimeout(timer);timer=setTimeout(()=>put('projects',active).catch(e=>toast(e.message)),500);}
 view.onclick=async e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.project){if(active)await put('projects',active);active=projects.find(p=>p.id===b.dataset.project);localStorage.setItem('convertshorts-current-project',active.id);render();}
 const id=b.dataset.generateShot||b.dataset.videoShot||b.dataset.deleteShot||b.dataset.moveShot;if(!id)return;const s=active.shots.find(s=>s.id===id);if(b.dataset.deleteShot){active.shots=active.shots.filter(v=>v!==s);await save();render();}else if(b.dataset.moveShot){const i=active.shots.indexOf(s);if(i>0)[active.shots[i-1],active.shots[i]]=[active.shots[i],active.shots[i-1]];await save();render();}else{await put('projects',active);await onReference({prompt:[active.brief,s.prompt].filter(Boolean).join('\n'),asset:assets.find(a=>a.id===s.asset),route:b.dataset.videoShot?'create-video':'create-image'});}};
 view.oninput=e=>{const n=e.target;for(const [key,field] of [['shotTitle','title'],['shotPrompt','prompt'],['shotDuration','duration'],['shotAsset','asset'],['shotStatus','status']])if(n.dataset[key]){const shot=active.shots.find(s=>s.id===n.dataset[key]);shot[field]=field==='duration'?Number(n.value):n.value;schedule();}};
 render();return ()=>{clearTimeout(timer);if(active)put('projects',active).catch(e=>toast(e.message));view.onclick=view.oninput=null;};
}
export async function mountCharacters(view,{toast}){
 const {all,get,put}=scopedStorage();
 let chars=(await all('characters')).filter(c=>!c.deleted),editing=null,refs=[];
 function render(){view.innerHTML=`<div class="page"><div class="page-head"><div><h1>Character identities</h1><p>Keep a character’s appearance and references consistent across your prompts.</p></div></div><div class="settings-grid"><section class="panel"><h2 id="character-form-title">${editing?'Edit character':'New character'}</h2><form id="character-form"><label>Name<input id="character-name" required maxlength="80" value="${esc(editing?.name||'')}"></label><label>Identity description<textarea id="character-description" rows="4" placeholder="Appearance, outfit, distinguishing details…">${esc(editing?.description||'')}</textarea></label><label>Reference portraits (up to 6)<input id="character-images" type="file" multiple accept="image/*"></label><div id="character-previews" class="references-row">${refs.map(r=>`<img width="72" height="72" src="${esc(r)}" alt="Character reference">`).join('')}</div><div class="row"><button class="primary-button">Save character</button><button id="reset-character" type="button" class="outline-button">New</button></div></form></section><section class="panel"><h2>Your characters</h2><div class="character-list">${chars.map(c=>`<article class="character-card">${c.references?.[0]?`<img src="${esc(c.references[0])}" alt="${esc(c.name)}">`:icon('image',35)}<div><h3>${esc(c.name)}</h3><p>${esc(c.description||'')}</p><button data-edit-character="${c.id}" class="outline-button">Edit</button><button data-delete-character="${c.id}" class="outline-button">Archive</button></div></article>`).join('')||'<p>No identities saved yet. Add a character and use it from any image or video composer.</p>'}</div></section></div></div>`;
 const el=id=>view.querySelector('#'+id);el('character-images').onchange=async e=>{try{for(const f of [...e.target.files].slice(0,6-refs.length))refs.push(await referenceData(f));el('character-previews').innerHTML=refs.map(r=>`<img width="72" height="72" src="${esc(r)}" alt="Character reference">`).join('');}catch(e){toast(e.message);}};
 el('character-form').onsubmit=async e=>{e.preventDefault();const c={...editing,id:editing?.id||uid(),name:el('character-name').value.trim(),description:el('character-description').value,references:refs,created:editing?.created||Date.now()};await put('characters',c);chars=(await all('characters')).filter(c=>!c.deleted);editing=null;refs=[];render();toast('Character identity saved.');};el('reset-character').onclick=()=>{editing=null;refs=[];render();};}
 view.onclick=async e=>{if(e.target.dataset.editCharacter){editing=chars.find(c=>c.id===e.target.dataset.editCharacter);refs=[...(editing.references||[])];render();}else if(e.target.dataset.deleteCharacter){const c=chars.find(c=>c.id===e.target.dataset.deleteCharacter);await put('characters',{...c,deleted:true});chars=chars.filter(v=>v!==c);render();}};
 render();return ()=>view.onclick=null;
}
export async function exportWorkspace(){const Zip=window.JSZip;if(!Zip)throw new Error('Backup engine is not ready.');const zip=new Zip(),manifest={format:'convertshorts-workspace-v1',stores:{}};for(const store of ['assets','folders','boards','projects','characters','presets']){manifest.stores[store]=[];for(const item of await all(store)){const {blob,_revision,_blobPath,_dirty,...record}=item;if(blob){record.mime=record.mime||blob.type;record.backupFile='files/'+uid();zip.file(record.backupFile,blob);}manifest.stores[store].push(record);}}zip.file('workspace.json',JSON.stringify(manifest));downloadBlob(await zip.generateAsync({type:'blob',compression:'STORE'}),'ConvertShorts-Workspace.zip');}
export async function importWorkspace(file){if(file.size>300*1024*1024)throw new Error('Use a backup smaller than 300 MB.');const zip=await window.JSZip.loadAsync(file);const source=zip.file('workspace.json');if(!source||source._data?.uncompressedSize>25000000)throw new Error('Choose a ConvertShorts workspace backup.');const text=await source.async('string');if(text.length>25000000)throw new Error('Backup metadata is too large.');const data=JSON.parse(text);if(data.format!=='convertshorts-workspace-v1')throw new Error('Unsupported backup format.');let count=0,total=0;for(const [store,items] of Object.entries(data.stores)){if(!['assets','folders','boards','projects','characters','presets'].includes(store)||!Array.isArray(items)||items.length>10000)throw new Error('Invalid backup data.');for(const item of items){if(typeof item.id!=='string'||item.id.length>120)throw new Error('Invalid record.');const record={...item,_revision:0,_blobPath:null};if(item.backupFile){const f=zip.file(item.backupFile);if(!f||f._data?.uncompressedSize>150*1024*1024)throw new Error('Invalid backup file.');total+=f._data?.uncompressedSize||0;if(total>300*1024*1024)throw new Error('The expanded backup exceeds 300 MB.');record.blob=new Blob([await f.async('uint8array')],{type:item.mime||'application/octet-stream'});delete record.backupFile;}await put(store,record);count++;}}return count;}
