import * as THREE from 'three';
export function createMannequin(){const root=new THREE.Group();root.name='Poseable mannequin';root.userData.mannequin=true;const mat=new THREE.MeshStandardMaterial({color:'#bfc9dd',roughness:.6,metalness:.05});
 const body=(parent,name,position,size)=>{const group=new THREE.Group();group.name=name;group.userData.poseJoint=true;group.position.fromArray(position);parent.add(group);const mesh=new THREE.Mesh(new THREE.CapsuleGeometry(size[0],size[1],8,16),mat);mesh.position.y=-size[1]/2;mesh.castShadow=true;group.add(mesh);return group;};
 const pelvis=new THREE.Group();pelvis.name='Pelvis';pelvis.position.y=1.05;pelvis.userData.poseJoint=true;root.add(pelvis);
 const torso=body(pelvis,'Spine',[0,.55,0],[.2,.45]);const head=body(torso,'Head',[0,.22,0],[.14,.08]);head.children[0].position.y=.06;
 for(const side of [-1,1]){const word=side===-1?'Left':'Right';const arm=body(torso,word+' shoulder',[side*.3,-.06,0],[.065,.3]);const forearm=body(arm,word+' elbow',[0,-.39,0],[.055,.28]);body(forearm,word+' wrist',[0,-.34,0],[.06,.06]);const leg=body(pelvis,word+' hip',[side*.13,-.02,0],[.09,.43]);const shin=body(leg,word+' knee',[0,-.51,0],[.07,.4]);const foot=body(shin,word+' ankle',[0,-.46,.04],[.075,.09]);foot.rotation.x=-Math.PI/2;}
 return root;}
export function poseJoints(object){const joints=[];object?.traverse(o=>{if(o.isBone||o.userData.poseJoint)joints.push(o);});return joints;}
export function applyPose(object,preset){const joints=poseJoints(object);joints.forEach(j=>{if(j.name!=='Pelvis'&&!j.name.includes('ankle'))j.rotation.set(0,0,0);});const rotate=(name,x,y,z)=>{const j=joints.find(j=>j.name===name);if(j)j.rotation.set(THREE.MathUtils.degToRad(x),THREE.MathUtils.degToRad(y),THREE.MathUtils.degToRad(z));};
 if(preset==='wave'){rotate('Right shoulder',0,0,150);rotate('Right elbow',0,0,-50);rotate('Head',0,0,-10);}else if(preset==='walk'){rotate('Left hip',-30,0,0);rotate('Right hip',25,0,0);rotate('Left knee',35,0,0);rotate('Left shoulder',20,0,0);rotate('Right shoulder',-20,0,0);}else if(preset==='sit'){rotate('Left hip',-90,0,0);rotate('Right hip',-90,0,0);rotate('Left knee',90,0,0);rotate('Right knee',90,0,0);}else if(preset==='tpose'){rotate('Left shoulder',0,0,-90);rotate('Right shoulder',0,0,90);}}
