let dbPromise;
export function database(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open('convertshorts-creative-studio',1);request.onupgradeneeded=()=>{for(const name of ['assets','jobs','folders','boards'])request.result.createObjectStore(name,{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return dbPromise;}
export async function put(store,value){const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error);});}
export async function all(store){const db=await database();return new Promise((resolve,reject)=>{const req=db.transaction(store).objectStore(store).getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
export async function get(store,id){const db=await database();return new Promise((resolve,reject)=>{const req=db.transaction(store).objectStore(store).get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
export const uid=()=>crypto.randomUUID();
export function fileType(file){if(file.type.startsWith('image/'))return 'image';if(file.type.startsWith('video/'))return 'video';if(file.type.startsWith('audio/'))return 'audio';if(/\.(glb|gltf|obj)$/i.test(file.name))return 'model';return 'file';}
export async function importFile(file,folder=''){if(file.size>150*1024*1024)throw new Error('Use files smaller than 150 MB for the local library.');const asset={id:uid(),name:file.name,type:fileType(file),mime:file.type,blob:file,folder,favorite:false,created:Date.now()};await put('assets',asset);return asset;}
export function downloadBlob(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
export async function downloadAsset(asset){if(asset.blob)return downloadBlob(asset.blob,asset.name);try{const r=await fetch(asset.remote,{mode:'cors'});if(!r.ok)throw new Error();downloadBlob(await r.blob(),asset.name);}catch{window.open(asset.remote,'_blank','noopener');}}
export async function referenceData(file){if(!file.type.startsWith('image/'))throw new Error('Choose a JPG, PNG or WebP image.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.86);}
