import {isExpired} from './customer.js';
export const STORES=['assets','jobs','folders','boards','projects','characters','presets'];
let dbPromise,namespace='';
export async function setNamespace(name=''){if(dbPromise)(await dbPromise).close();dbPromise=null;namespace=name;}
export function currentNamespace(){return namespace;}
export function database(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open('convertshorts-creative-studio'+(namespace?'-'+namespace:''),2);request.onupgradeneeded=()=>{for(const name of STORES)if(!request.result.objectStoreNames.contains(name))request.result.createObjectStore(name,{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return dbPromise;}
export async function put(store,value,options={}){if(!options.remote)value={...value,updated:Date.now(),_dirty:true};const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>{if(!options.remote)window.dispatchEvent(new CustomEvent('studio-storage-changed',{detail:{store,id:value.id}}));resolve(value);};tx.onerror=()=>reject(tx.error);});}
export async function remove(store,id){const value=await get(store,id);if(value)await put(store,{...value,deleted:true});}
export async function all(store){const db=await database();return new Promise((resolve,reject)=>{const req=db.transaction(store).objectStore(store).getAll();req.onsuccess=()=>resolve(req.result.filter(i=>!isExpired(i)));req.onerror=()=>reject(req.error);});}
export async function get(store,id){const db=await database();return new Promise((resolve,reject)=>{const req=db.transaction(store).objectStore(store).get(id);req.onsuccess=()=>resolve(isExpired(req.result)?undefined:req.result);req.onerror=()=>reject(req.error);});}
export const uid=()=>crypto.randomUUID();
export function fileType(file){if(file.type.startsWith('image/'))return 'image';if(file.type.startsWith('video/'))return 'video';if(file.type.startsWith('audio/'))return 'audio';if(/\.(ply|splat|spz|sog|ksplat)$/i.test(file.name))return 'world';if(/\.(glb|gltf|fbx|obj)$/i.test(file.name))return 'model';return 'file';}
export async function importFile(file,folder=''){if(file.size>150*1024*1024)throw new Error('Use files smaller than 150 MB for the local library.');const asset={id:uid(),name:file.name,type:fileType(file),mime:file.type,blob:file,folder,favorite:false,created:Date.now()};await put('assets',asset);return asset;}
export function downloadBlob(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
export async function mediaAsset(asset){if(isExpired(asset))throw Error("This cloud copy has expired.");if(asset?._blobPath&&!asset.blob)return (await import("./cloud.js")).resolveCloudMedia(asset);return asset;}
export async function downloadAsset(asset){asset=await mediaAsset(asset);if(asset.blob)return downloadBlob(asset.blob,asset.name);try{const r=await fetch(asset.remote,{mode:'cors'});if(!r.ok)throw new Error();downloadBlob(await r.blob(),asset.name);}catch{window.open(asset.remote,'_blank','noopener');}}
export async function referenceData(file){if(!file.type.startsWith('image/'))throw new Error('Choose a JPG, PNG or WebP image.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.86);}

// An editor opened in one account must never write into a subsequently selected workspace.
export function scopedStorage(){const scope=namespace;const check=()=>{if(scope!==namespace)throw new Error('Workspace changed. Reopen this tool.');};return {check,isCurrent:()=>scope===namespace,importFile:(f,d)=>{check();return importFile(f,d);},all:async s=>{check();const result=await all(s);check();return result;},get:async(s,k)=>{check();const result=await mediaAsset(await get(s,k));check();return result;},put:(s,v,o)=>{check();return put(s,v,o);}};}
