import {escape as esc} from './icons.js';
export const WORKFLOWS=[
 ['create-image','Create image','AI generation · coming soon',['Write a description and choose a model.','For a reference photo, choose an image editing or reference-capable model and upload it.','Set resolution and outputs, then Generate. Open or download the result in My Library.']],
 ['create-video','Create video','AI generation · coming soon',['Choose text-to-video for a prompt, or image-to-video and upload a starting image.','Set Duration, resolution and generated audio when the selected model supports them.','Generate and wait for the completed clip. Open it in My Library to play or download.']],
 ['create-audio','Create audio','AI generation · coming soon',['The initial launch includes ACE-Step for songs or instrumentals and MiniMax for songs with lyrics. Speech and sound effects are planned.','Enter music style and lyrics for a song. ACE-Step supports requested duration; MiniMax chooses its length. Vocal and exclusion preferences are guidance.','For speech, enter the words and choose a voice. Generate, then play or download your audio.']],
 ['create-object','Create 3D object','AI generation · coming soon',['Upload a clear image of a single object and choose a compatible model.','Review the model settings and Generate.','Open the completed model in Edit 3D, then arrange it or export it.']],
 ['create-world','Create 3D world','AI generation · coming soon',['Choose a world model and upload the scene image it requires. World generation is planned after the initial image, video and music launch.','Fill in the required scene labels or prompt shown for that model, then Generate.','Open supported world files in Explore Worlds. Different providers may return different file formats.']],
 ['canvas','AI Canvas','Drawing and PNG export are free',['Import an image, try the example, or choose Brush / Rectangle and draw. The checkerboard is transparency.','Select a layer to move it; use Undo or Delete selected layer to revise.','Export PNG, or Use composition in AI when AI generation launches. For a repair, paint with Mask before choosing Edit masked region with AI.']],
 ['edit-3d','Edit 3D','Local tools are free; AI rendering is coming soon',['Add a box, sphere or character, or import a GLB / OBJ model or supported splat environment.','Select an object; use Move, Rotate or Scale and adjust your camera / lighting.','Capture PNG, Export GLB or save the scene. An AI camera render sends a captured image to an AI model; splats are separate from mesh GLB exports.']],
 ['edit-world','Explore Worlds','Local viewer is free',['Import a supported PLY / SPLAT / SPZ / SOG / KSPLAT world file, or open a world asset from My Library.','Use the camera controls to explore and Save camera to keep a viewpoint.','Capture PNG or Export original. This viewer does not generate a world by itself.']],
 ['edit-image','Edit Image','Local editor is free',['Use File → Open to import a photo, or File → New for a document.','Work with layers, selections, brushes and adjustments in the photo editor.','Save or export inside the editor before leaving. Import that file into My Library to reuse it.']],
 ['ai-edit','AI image editing','AI generation · coming soon',['Choose an editing model and upload its required image references.','Describe the change. For a masked repair, use AI Canvas to paint the mask first.','Generate, then compare and download the completed image.']],
 ['edit-video','Edit Video','Local editor is free',['Choose library media and Import selected, or import files inside the video editor.','Choose New sequence from clip, then trim and arrange tracks inside the editor.','Export inside the editor, then Save exports to library. Export before navigating away.']],
 ['quick-video','Quick timeline','Local editor is free',['Import a video, audio or image in the quick editor.','Arrange clips and adjust timing in the timeline.','Use the editor export controls and save the file before leaving.']],
 ['video-vfx','Video VFX','AI generation · coming soon',['Choose a video model that accepts a source video for the effect you need.','Upload the required video in its media field and describe the change.','Review Duration and other supported settings, then Generate. This is an AI transform, not the timeline editor.']],
 ['background-change','Video Background Change','Chroma key is free; AI masking is coming soon',['Open a video, choose a replacement background, and use chroma key for a solid-color backdrop.','For a general scene, Remove background with AI requests a provider mask; the quality depends on that model.','Preview, then Export video & save to library. This workflow does not include ArtCraft’s SwitchX relighting service.']],
 ['image-background','Image Background Change','AI generation · coming soon',['Choose background removal or background replacement and upload an image.','Describe the replacement when required.','Generate and download the image. Use Video Background Change for moving clips.']],
 ['moodboard','Moodboard','Local tool is free',['Create a board, then add reference images, notes, colors or sections.','Drag items into place to plan the style of a shot.','The board saves automatically. Export PNG to share it; creating a board does not generate an image.']],
 ['frame-extractor','Frame Extractor','Local tool is free',['Open a local video and scrub to the time you want.','Capture frame for one still, or Capture burst for a sequence.','Save frames to library, download a PNG, or Download all frames as a ZIP.']],
 ['library','My Library and folders','Local storage; private cloud sync after sign-in',['Import files or save generated and edited results here. Open an asset to play it, rename it or reuse it.','Use folders, tags, favorites and search to organize work. Trash supports restore.','Download important files or export a workspace backup. Browser data can be cleared; sign in for 500 MB of private cloud media storage. Cloud copies expire 30 days from first save.']],
 ['projects','Projects and shot lists','Local projects; cloud sync after sign-in',['Create a project and add shots with prompts, references and planned models.','Generate an image or video from a shot, then keep its result with your assets.','Save project, export JSON or use private workspace sync.']],
 ['characters','Characters','Saved references; AI generation is coming soon',['Save a character name, description and reference images.','Choose that character in the generator’s More settings to add its description and references.','Character references help guide appearance; they do not guarantee identical identity across models.']]
];
export function workflowHelp(route){const w=WORKFLOWS.find(w=>w[0]===route);return w?`<details class="workflow-help"><summary>How to use ${esc(w[1])}</summary><p>${esc(w[2])}</p><ol>${w[3].map(step=>`<li>${esc(step)}</li>`).join('')}</ol><a href="#guide">See all studio workflows →</a></details>`:'';}
export function workflowGuide(){return `<div class="guide-grid">${WORKFLOWS.map(([route,name,note,steps])=>`<section class="panel"><h2>${esc(name)}</h2><p class="workflow-note">${esc(note)}</p><ol>${steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol><a class="outline-button" href="#${route}">Open ${esc(name)}</a></section>`).join('')}</div>`;}
