import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {SplatMesh,SparkRenderer} from './vendor/spark/dist/spark.module.js';
import {all,put,get,uid,downloadBlob} from './storage.js';
import {escape as esc} from './icons.js';
export async function mountWorld(view,{toast,asset,assetURL,onAsset}){
 view.innerHTML=`<section><div class="scene-toolbar"><strong>World Studio</strong><label class="outline-button">Import PLY / SPLAT / SPZ<input type="file" id="world-file" accept=".ply,.splat,.spz,.sog,.ksplat" hidden></label><select id="world-library" aria-label="World from library"><option value="">Open from library…</option>${(await all('assets')).filter(a=>a.type==='world'&&!a.deleted).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select><button id="world-capture">Capture PNG</button><button id="world-bookmark">Save camera</button><button id="world-export">Export original</button></div><div class="scene-layout world-layout"><aside class="scene-side"><h3>EXPLORATION</h3><label>Navigation<select id="world-mode"><option value="orbit">Orbit</option><option value="walk">Walk / fly</option></select></label><label>Move speed<input id="world-speed" type="range" min=".1" max="8" step=".1" value="2"></label><label>Field of view<input id="world-fov" type="range" min="25" max="100" value="65"></label><label>World rotation °<input id="world-rotation" type="number" step="15" value="0"></label><label>World scale<input id="world-scale" type="number" step=".1" min=".01" value="1"></label><h3>SAVED CAMERAS</h3><div id="world-cameras"></div><p class="small-note">Orbit: drag and scroll. Walk: click the viewport, then W/A/S/D to move, Q/E for height, drag to look. Escape releases control.</p><p id="world-status">Import a Gaussian-splat world to explore it.</p></aside><div class="scene-viewport" id="world-viewport"><span class="scene-overlay">GAUSSIAN SPLAT · WEBGL2</span></div></div></section>`;
 const el=id=>view.querySelector('#'+id),viewport=el('world-viewport');let disposed=false,splat=null,opened=null,frame=0,timer,bookmarks=[],last=performance.now(),loadTicket=0;
 const renderer=new THREE.WebGLRenderer({antialias:false,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#111621');viewport.prepend(renderer.domElement);
 const scene=new THREE.Scene(),spark=new SparkRenderer({renderer});scene.add(spark);const camera=new THREE.PerspectiveCamera(65,1,.02,1000);camera.position.set(0,1,4);const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1,0);orbit.enableDamping=true;
 const keys=new Set(),clock=new THREE.Clock(),direction=new THREE.Vector3();let drag=null,yaw=0,pitch=0;
 const resize=()=>{camera.aspect=viewport.clientWidth/viewport.clientHeight;camera.updateProjectionMatrix();renderer.setSize(viewport.clientWidth,viewport.clientHeight,false);};const observer=new ResizeObserver(resize);observer.observe(viewport);resize();
 function animate(){if(disposed)return;const dt=Math.min(.1,clock.getDelta());if(el('world-mode').value==='walk'){const speed=Number(el('world-speed').value)*dt;direction.set((keys.has('d')?1:0)-(keys.has('a')?1:0),(keys.has('e')?1:0)-(keys.has('q')?1:0),(keys.has('s')?1:0)-(keys.has('w')?1:0));direction.applyQuaternion(camera.quaternion);camera.position.addScaledVector(direction,speed);}else orbit.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate);}animate();
 const keydown=e=>{if(e.target.closest('input,select,textarea'))return;keys.add(e.key.toLowerCase());},keyup=e=>keys.delete(e.key.toLowerCase());window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);
 renderer.domElement.addEventListener('pointerdown',e=>{if(el('world-mode').value==='walk'){drag=[e.clientX,e.clientY];renderer.domElement.setPointerCapture(e.pointerId);}});renderer.domElement.addEventListener('pointerup',()=>drag=null);renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-drag[0])*.004;pitch=Math.max(-1.5,Math.min(1.5,pitch-(e.clientY-drag[1])*.004));camera.rotation.set(pitch,yaw,0,'YXZ');drag=[e.clientX,e.clientY];});
 async function save(){if(opened)await put('boards',{id:'world-'+opened.id,kind:'world',name:opened.name,nodes:[],bookmarks,rotation:splat?.rotation.y||0,scale:splat?.scale.x||1,camera:{position:camera.position.toArray(),target:orbit.target.toArray(),quaternion:camera.quaternion.toArray(),fov:camera.fov},updated:Date.now()});}
 function cameras(){el('world-cameras').innerHTML=bookmarks.map((b,i)=>`<button data-world-camera="${i}">${esc(b.name)}</button>`).join('');}
 async function load(a){const own=++loadTicket;try{el('world-status').textContent='Loading world…';const blob=a.blob||await(await fetch(a.remote)).blob();if(blob.size>150*1024*1024)throw new Error('Use a world below 150 MB.');const candidate=new SplatMesh({fileBytes:await blob.arrayBuffer(),fileName:a.name});await candidate.initialized;if(disposed||own!==loadTicket){candidate.dispose();return;}if(splat){scene.remove(splat);splat.dispose();}splat=candidate;opened={...a,blob};scene.add(splat);const stored=await get('boards','world-'+a.id);bookmarks=stored?.bookmarks||[];if(stored?.camera){camera.position.fromArray(stored.camera.position);orbit.target.fromArray(stored.camera.target);camera.fov=stored.camera.fov;camera.updateProjectionMatrix();splat.rotation.y=stored.rotation||0;splat.scale.setScalar(stored.scale||1);}el('world-status').textContent='Loaded '+splat.numSplats.toLocaleString()+' Gaussian splats.';cameras();}catch(e){el('world-status').textContent='Could not open this world: '+e.message;toast('Import a valid PLY, SPLAT or SPZ Gaussian-splat file. ZIP archives must be extracted first.');}}
 el('world-file').onchange=async e=>{if(!e.target.files[0])return;const f=e.target.files[0],a={id:uid(),name:f.name,type:'world',blob:f,created:Date.now()};await put('assets',a);await onAsset();await load(a);};el('world-library').onchange=async e=>{const a=await get('assets',e.target.value);if(a)await load(a);};
 el('world-mode').onchange=e=>{orbit.enabled=e.target.value==='orbit';if(!orbit.enabled){camera.rotation.order='YXZ';yaw=camera.rotation.y;pitch=camera.rotation.x;}};
 el('world-fov').oninput=e=>{camera.fov=Number(e.target.value);camera.updateProjectionMatrix();};el('world-rotation').oninput=e=>{if(splat)splat.rotation.y=THREE.MathUtils.degToRad(Number(e.target.value));};el('world-scale').oninput=e=>{if(splat)splat.scale.setScalar(Math.max(.01,Number(e.target.value)));};
 el('world-bookmark').onclick=async()=>{bookmarks.push({name:'Camera '+(bookmarks.length+1),position:camera.position.toArray(),target:orbit.target.toArray(),fov:camera.fov});cameras();await save();toast('Camera saved.');};el('world-cameras').onclick=e=>{const index=e.target.dataset.worldCamera;if(index===undefined)return;const b=bookmarks[Number(index)];camera.position.fromArray(b.position);orbit.target.fromArray(b.target);camera.fov=b.fov;camera.updateProjectionMatrix();};
 el('world-export').onclick=()=>opened?downloadBlob(opened.blob,opened.name):toast('Open a world first.');el('world-capture').onclick=async()=>{renderer.render(scene,camera);const blob=await new Promise(r=>renderer.domElement.toBlob(r));if(!blob)return;const a={id:uid(),name:'World-Camera-'+Date.now()+'.png',type:'image',blob,created:Date.now()};await put('assets',a);await onAsset();downloadBlob(blob,a.name);};
 if(asset)await load(asset);
 return ()=>{save().catch(e=>toast(e.message));disposed=true;loadTicket++;cancelAnimationFrame(frame);observer.disconnect();orbit.dispose();splat?.dispose();spark.dispose();renderer.dispose();keys.clear();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);};
}
