import {prepareGeneration,MODELS,StudioError,validateQueueURL,normalizeMedia} from './studio-core.mjs';
import {CREDIT_PLANS,PRICING_VERSION,quoteCredits,supportsHostedPricing} from '../apps/studio/pricing.js';
// Supabase Edge Function. Uses runtime secrets; no credential is bundled or returned.
const env=(k:string)=>Deno.env.get(k)||'';
const base=()=>env('SUPABASE_URL'),secret=()=>env('SUPABASE_SERVICE_ROLE_KEY');
const cors=(req:Request)=>({'Access-Control-Allow-Origin':req.headers.get('origin')==='https://convertshorts.com'?'https://convertshorts.com':'null','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Cache-Control':'no-store'});
const reply=(req:Request,value:unknown,status=200)=>Response.json(value,{status,headers:cors(req)});
const hostedEnabled=()=>env('CONVERTSHORTS_HOSTED_ENABLED')==='true'&&!!env('CONVERTSHORTS_FAL_KEY');
const plans=()=>JSON.parse(env('CONVERTSHORTS_STRIPE_PLANS')||'[]').flatMap((p:any)=>{const offer=CREDIT_PLANS.find(o=>o.id===p.id);return offer&&/^price_\w+$/.test(p.price||'')?[{...offer,price:p.price}]:[];});
const merchantEnabled=()=>hostedEnabled()&&!!(env('CONVERTSHORTS_STRIPE_SECRET_KEY')&&env('CONVERTSHORTS_STRIPE_WEBHOOK_SECRET')&&plans().length);
async function db(path:string,method='GET',body?:unknown){const r=await fetch(base()+'/rest/v1/'+path,{method,headers:{apikey:secret(),Authorization:'Bearer '+secret(),'Content-Type':'application/json',Prefer:'return=representation'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok){if(d.message==='Insufficient workspace credits')throw new StudioError('Not enough credits. Choose a credit pack in Usage & billing.',402);throw Error('Billing data request failed');}return d;}
async function stripe(path:string,body?:Record<string,string>){const r=await fetch('https://api.stripe.com/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+env('CONVERTSHORTS_STRIPE_SECRET_KEY'),'Content-Type':'application/x-www-form-urlencoded'},body:body?new URLSearchParams(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error?.message||'Stripe request failed');return d;}
export async function verifySignature(text:string,header:string,key:string){const parts=header.split(','),time=parts.find(p=>p.startsWith('t='))?.slice(2),signatures=parts.filter(p=>p.startsWith('v1=')).map(p=>p.slice(3));if(!time||Math.abs(Date.now()/1000-Number(time))>300)return false;const cryptoKey=await crypto.subtle.importKey('raw',new TextEncoder().encode(key),{name:'HMAC',hash:'SHA-256'},false,['sign']);const digest=new Uint8Array(await crypto.subtle.sign('HMAC',cryptoKey,new TextEncoder().encode(time+'.'+text)));const expected=Array.from(digest,b=>b.toString(16).padStart(2,'0')).join('');return signatures.some(s=>{if(s.length!==expected.length)return false;let difference=0;for(let i=0;i<s.length;i++)difference|=s.charCodeAt(i)^expected.charCodeAt(i);return difference===0;});}
export async function handleBilling(req:Request){try{
 if(req.method==='OPTIONS')return new Response(null,{headers:cors(req)});
 if(new URL(req.url).searchParams.get('action')==='config')return reply(req,{enabled:merchantEnabled(),generationEnabled:hostedEnabled(),pricingVersion:PRICING_VERSION,hostedModels:MODELS.filter(supportsHostedPricing).map(m=>m.id),plans:CREDIT_PLANS.map(p=>({...p,available:merchantEnabled()&&plans().some((v:any)=>v.id===p.id)}))});
 if(req.headers.has('stripe-signature')){
  if(!env('CONVERTSHORTS_STRIPE_WEBHOOK_SECRET'))return reply(req,{error:'Webhook not configured'},503);const raw=await req.text();if(raw.length>1000000||!await verifySignature(raw,req.headers.get('stripe-signature')!,env('CONVERTSHORTS_STRIPE_WEBHOOK_SECRET')))return reply(req,{error:'Invalid signature'},400);const e=JSON.parse(raw),o=e.data.object;
  if(e.type==='checkout.session.completed'&&o.mode==='payment'&&o.payment_status==='paid'){
   const line=await stripe('checkout/sessions/'+encodeURIComponent(o.id)+'/line_items');const p=plans().find((p:any)=>p.mode==='payment'&&p.price===line.data?.[0]?.price?.id);if(!p)throw Error('Unknown paid price');const u=o.client_reference_id;if(!/^[0-9a-f-]{36}$/.test(u||''))throw Error('Missing account reference');const accounts=await db('convertshorts_billing_accounts?user_id=eq.'+u);await db('rpc/convertshorts_apply_billing_event','POST',{event_id:e.id,u,customer:o.customer,plan_name:accounts[0]?.plan||'Free',subscription:accounts[0]?.subscription_id||null,credits:p.credits,source_name:'pack',start_at:new Date(e.created*1000).toISOString(),months:1});
  }else if(e.type==='invoice.paid'){
   const subscription=o.subscription||o.parent?.subscription_details?.subscription;if(subscription){const sub=await stripe('subscriptions/'+encodeURIComponent(subscription));const price=sub.items.data[0]?.price,p=plans().find((p:any)=>p.mode==='subscription'&&p.price===price?.id),u=sub.metadata?.convertshorts_user;if(p&&u){await db('rpc/convertshorts_apply_billing_event','POST',{event_id:e.id,u,customer:sub.customer,plan_name:p.name,subscription:sub.id,credits:p.credits,source_name:'subscription',start_at:new Date((o.lines.data[0]?.period?.start||e.created)*1000).toISOString(),months:price.recurring?.interval==='year'?12:1});}}
  }else if(e.type==='customer.subscription.deleted')await db('convertshorts_billing_accounts?subscription_id=eq.'+encodeURIComponent(o.id),'PATCH',{plan:'Free',subscription_id:null});
  return reply(req,{received:true});
 }
 const origin=req.headers.get('origin');if(origin&&origin!=='https://convertshorts.com')return reply(req,{error:'Use ConvertShorts'},403);
 const authorization=req.headers.get('authorization');if(!authorization?.startsWith('Bearer '))return reply(req,{error:'Sign in first'},401);const userResponse=await fetch(base()+'/auth/v1/user',{headers:{apikey:env('SUPABASE_ANON_KEY'),Authorization:authorization}});if(!userResponse.ok)return reply(req,{error:'Sign in again'},401);const user=await userResponse.json();
 const accounts=await db('convertshorts_billing_accounts?user_id=eq.'+user.id),account=accounts[0];
 if(new URL(req.url).searchParams.get('action')==='status'){
  const id=new URL(req.url).searchParams.get('job');if(!/^[0-9a-f-]{36}$/.test(id||''))return reply(req,{error:'Invalid job'},400);const jobs=await db('convertshorts_generation_requests?id=eq.'+id+'&user_id=eq.'+user.id),job=jobs[0];if(!job)return reply(req,{error:'Job not found'},404);if(job.status==='FAILED_REFUNDED')return reply(req,{error:'Generation failed. Workspace credits refunded.'},422);if(!job.provider)return reply(req,{error:'Submission status is uncertain. Ask the owner to review this request.'},409);
  const key=env('CONVERTSHORTS_FAL_KEY');for(const field of ['status_url','response_url'])validateQueueURL(job.provider[field]);const status=await fetch(job.provider.status_url,{headers:{Authorization:'Key '+key},signal:AbortSignal.timeout(30000)});if(!status.ok)return reply(req,{error:'Provider status temporarily unavailable'},502);const d=await status.json();if(d.status==='COMPLETED'){
   const result=await fetch(job.provider.response_url,{headers:{Authorization:'Key '+key},signal:AbortSignal.timeout(30000)});if(!result.ok){if([400,422].includes(result.status)){await db('rpc/convertshorts_refund_generation','POST',{j:id});return reply(req,{error:'Generation failed. Workspace credits refunded.'},422);}return reply(req,{error:'Provider result temporarily unavailable'},502);}
   let media;try{media=normalizeMedia(await result.json(),MODELS.find(m=>m.id===job.model)?.kind);}catch{await db('rpc/convertshorts_refund_generation','POST',{j:id});return reply(req,{error:'Generation produced no media. Workspace credits refunded.'},422);}await db('convertshorts_generation_requests?id=eq.'+id,'PATCH',{status:'COMPLETED'});return reply(req,{status:'COMPLETED',media});
  }if(['FAILED','CANCELLED','ERROR'].includes(d.status)){await db('rpc/convertshorts_refund_generation','POST',{j:id});return reply(req,{error:'Generation failed. Workspace credits refunded.'},422);}return reply(req,{status:d.status,queuePosition:d.queue_position});
 }
 if(req.method==='GET'){const grants=await db('convertshorts_credit_grants?user_id=eq.'+user.id+'&valid_from=lte.'+encodeURIComponent(new Date().toISOString()));return reply(req,{plan:account?.plan||'Free',credits:grants.filter((g:any)=>!g.expires_at||Date.parse(g.expires_at)>Date.now()).reduce((n:number,g:any)=>n+g.remaining,0)});}
 const raw=await req.text();if(raw.length>4200000)return reply(req,{error:'Request too large'},413);const body=JSON.parse(raw),returnURL='https://convertshorts.com/apps/#billing';
 if(body.action==='quote'||body.action==='generate'){
  if(!hostedEnabled())return reply(req,{error:'Hosted credits are not available yet. You can use your own provider key.'},503);const generation=prepareGeneration(body.generation);let quote;try{quote=quoteCredits(generation.endpoint,generation.input);}catch(e){throw new StudioError(e instanceof Error?e.message:'This model is not priced.');}
  if(body.action==='quote')return reply(req,{credits:quote.credits,retailUsd:quote.retailUsd,version:quote.version});
  if(body.expectedCredits!==quote.credits||body.pricingVersion!==quote.version)return reply(req,{error:'The generation price changed. Review the current credits and submit again.',quote:{credits:quote.credits,version:quote.version}},409);
  const id=crypto.randomUUID();await db('rpc/convertshorts_reserve_credits','POST',{u:user.id,j:id,m:generation.model.id,amount:quote.credits});
  let response;try{response=await fetch('https://queue.fal.run/'+generation.endpoint,{method:'POST',headers:{Authorization:'Key '+env('CONVERTSHORTS_FAL_KEY'),'Content-Type':'application/json'},body:JSON.stringify(generation.input),signal:AbortSignal.timeout(40000)});}catch{return reply(req,{error:'Provider submission is uncertain. Credits are reserved; ask the owner to review job '+id},502);}
  if(!response.ok){await db('rpc/convertshorts_refund_generation','POST',{j:id});return reply(req,{error:'Provider rejected the request. Credits refunded.'},422);}const provider=await response.json();for(const key of ['status_url','response_url','cancel_url'])if(provider[key])validateQueueURL(provider[key]);await db('convertshorts_generation_requests?id=eq.'+id,'PATCH',{provider,status:provider.status||'IN_QUEUE'});return reply(req,{cloudJobID:id,requestId:provider.request_id,status:provider.status||'IN_QUEUE'},202);
 }
 if(!merchantEnabled())return reply(req,{error:'Hosted credits and checkout are not available yet.'},503);
 if(body.action==='portal'){if(!account?.customer_id)return reply(req,{error:'No Stripe customer for this account yet'},400);const portal=await stripe('billing_portal/sessions',{customer:account.customer_id,return_url:returnURL});return reply(req,{url:portal.url});}
 if(body.action==='checkout'){const p=plans().find((p:any)=>p.id===body.plan);if(!p)return reply(req,{error:'Unknown plan'},400);const price=await stripe('prices/'+encodeURIComponent(p.price));if(!price.active||price.unit_amount!==p.amountCents||price.currency!==p.currency||(p.mode==='subscription'?(price.recurring?.interval!==p.interval||price.recurring?.interval_count!==1):!!price.recurring))return reply(req,{error:'Checkout price is being updated. Please try later.'},503);const params:Record<string,string>={mode:p.mode,'line_items[0][price]':p.price,'line_items[0][quantity]':'1',client_reference_id:user.id,success_url:returnURL,cancel_url:returnURL};if(account?.customer_id)params.customer=account.customer_id;else params.customer_email=user.email;if(p.mode==='subscription')params['subscription_data[metadata][convertshorts_user]']=user.id;else params.customer_creation='always';const checkout=await stripe('checkout/sessions',params);return reply(req,{url:checkout.url});}
 return reply(req,{error:'Unsupported billing action'},400);
 }catch(e){return reply(req,{error:e instanceof Error?e.message:'Billing request failed'},e instanceof StudioError?e.status:502);}}
if(import.meta.main)Deno.serve(handleBilling);
