import {$,shell,upload,wireUpload,bitmap,dimensions,number,drawFit,canvasBlob,download,clearDownloads,status,bytes,baseName,presetSelect} from './lib/common.js';
import {setBusy} from './app.js';
export function mountImage(root){let source=null,file=null,disposed=false;
root.innerHTML=shell('Image tools','The right size. The right format. Ready to share.',`<div class="tool-layout"><section class="panel">${upload('image-file','image/jpeg,image/png,image/webp','Choose an image or drop it here','JPG, PNG or WebP · processed on your device')}<div class="preview"><div class="empty" id="image-empty"><b>▧</b>Your image preview appears here.</div><canvas id="image-canvas" hidden></canvas></div><p class="meta" id="image-info">No image selected</p></section><section class="panel settings"><h2>Resize & export</h2>${presetSelect('image-preset')}<div class="row"><label>Width (px)<input id="image-w" type="number" min="1" max="4096" value="1080"></label><label>Height (px)<input id="image-h" type="number" min="1" max="4096" value="1080"></label></div><label class="check"><input id="image-lock" type="checkbox" checked> Keep original proportions</label><label>Fit<select id="image-fit"><option value="contain">Fit whole image</option><option value="cover">Crop to fill</option></select></label><label>Horizontal crop position<input id="image-x" type="range" min="0" max="100" value="50"></label><label>Vertical crop position<input id="image-y" type="range" min="0" max="100" value="50"></label><label>Background<input id="image-bg" type="color" value="#ffffff"></label><label class="check"><input id="image-transparent" type="checkbox" checked> Transparent background (PNG / WebP)</label><hr class="divider"><label>Format<select id="image-format"><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></label><label>Quality <span id="image-quality-value">85%</span><input id="image-quality" type="range" min="10" max="100" value="85"></label><label>Maximum file size (KB, optional)<input id="image-target" type="number" min="1" placeholder="For example, 200"></label><p class="hint">For JPG / WebP, quality is reduced to approach the size limit. Dimensions stay as selected. PNG compression has no quality slider.</p><button class="primary wide" id="image-export" disabled>Export image</button></section></div>`);
const canvas=$('#image-canvas'),ctx=canvas.getContext('2d');
function render(){if(!source)return;try{const {w,h}=dimensions($('#image-w').value,$('#image-h').value);canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);if(!$('#image-transparent').checked||$('#image-format').value==='image/jpeg'){ctx.fillStyle=$('#image-bg').value;ctx.fillRect(0,0,w,h);}drawFit(ctx,source,w,h,$('#image-fit').value,Number($('#image-x').value)/100,Number($('#image-y').value)/100);canvas.hidden=false;$('#image-empty').hidden=true;}catch(e){status(e.message,true);}}
wireUpload('image-file',async files=>{const next=await bitmap(files[0]);if(disposed){next.close();return;}source?.close();source=next;file=files[0];const scale=Math.min(1,4096/source.width,4096/source.height);$('#image-w').value=Math.round(source.width*scale);$('#image-h').value=Math.round(source.height*scale);$('#image-info').textContent=`${file.name} · ${source.width} × ${source.height} · ${bytes(file.size)}`;$('#image-export').disabled=false;clearDownloads();status('');render();});
$('#image-preset').onchange=e=>{if(e.target.value==='custom')return;const [w,h]=e.target.value.split(',');$('#image-w').value=w;$('#image-h').value=h;$('#image-lock').checked=false;render();};
for(const id of ['image-w','image-h'])$(`#${id}`).oninput=()=>{if(source&&$('#image-lock').checked){if(id==='image-w')$('#image-h').value=Math.round(Number($('#image-w').value)*source.height/source.width);else $('#image-w').value=Math.round(Number($('#image-h').value)*source.width/source.height);}$('#image-preset').value='custom';render();};
for(const id of ['image-fit','image-x','image-y','image-bg','image-transparent','image-format','image-quality'])$(`#${id}`).oninput=()=>{$('#image-quality-value').textContent=`${$('#image-quality').value}%`;$('#image-quality').disabled=$('#image-format').value==='image/png';render();};
$('#image-export').onclick=async()=>{if(!source)return;const button=$('#image-export');button.disabled=true;setBusy(true);try{dimensions($('#image-w').value,$('#image-h').value);render();clearDownloads();const type=$('#image-format').value,q=Number($('#image-quality').value)/100;const target=$('#image-target').value?number($('#image-target').value,1,100000,'Target size')*1024:0;let blob=await canvasBlob(canvas,type,q);if(target&&blob.size>target&&type!=='image/png'){let low=.01,high=q,best=null;for(let i=0;i<9;i++){const quality=(low+high)/2,candidate=await canvasBlob(canvas,type,quality);if(candidate.size<=target){best=candidate;low=quality;}else high=quality;}blob=best||await canvasBlob(canvas,type,.01);}if(blob.type!==type)throw Error('This browser does not support that output format. Choose PNG or JPG.');download(blob,`${baseName(file.name)}-${canvas.width}x${canvas.height}.${type.split('/')[1].replace('jpeg','jpg')}`);status(`${bytes(file.size)} → ${bytes(blob.size)}. ${target&&blob.size>target?'The size limit could not be reached at these dimensions. Reduce the width or height and try again.':'Your image is ready.'}`);}catch(e){status(e.message,true);}finally{button.disabled=false;setBusy(false);}};
return()=>{disposed=true;source?.close();};}
