import {StudioError,signJob,verifyJob,validateSchema} from '../server/studio-core.mjs';
import {WORLD_MODELS} from '../server/world-models.mjs';
const reply=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function requestProvider(path,key,body){const r=await fetch('https://api.worldlabs.ai/marble/v1/'+path,{method:body?'POST':'GET',headers:{'WLT-Api-Key':key,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,redirect:'error',signal:AbortSignal.timeout(40000)});const d=await r.json();if(!r.ok)throw new StudioError(typeof d.detail==='string'?d.detail.slice(0,250):'World Labs rejected the request. Check your API key, credits and inputs.',r.status);return d;}
async function handle(req,method){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new StudioError('Use this website.',403);const key=req.headers.get('x-world-key');if(!key||key.length<8||key.length>512||!/^[\x21-\x7e]+$/.test(key))throw new StudioError('Connect your World Labs API key in Settings.',401);
 if(method==='POST'){const text=await req.text();if(text.length>3200000)throw new StudioError('Request is too large.',413);const body=JSON.parse(text),model=WORLD_MODELS.find(m=>m.id===body.model);if(!model)throw new StudioError('Unsupported world model.');const input=validateSchema(body.input,model.schema);const prompt=String(input.prompt||body.prompt||'').trim();if(!prompt&&!input.image_url)throw new StudioError('Describe a world or attach an image.');const world_prompt=input.image_url?{type:'image',image_prompt:{source:'uri',uri:input.image_url},text_prompt:prompt||undefined,is_pano:!!input.is_pano}:{type:'text',text_prompt:prompt};const d=await requestProvider('worlds:generate',key,{model:model.endpoint,display_name:input.display_name||undefined,seed:input.seed,permission:{public:false},world_prompt});if(!/^[a-zA-Z0-9_-]{1,180}$/.test(d.operation_id||''))throw new StudioError('The provider returned an invalid job ID.',502);return reply({token:signJob({operation_id:d.operation_id,provider:'worldlabs',model:model.id},key),requestId:d.operation_id,status:'IN_PROGRESS'},202);}
 const job=verifyJob(new URL(req.url).searchParams.get('token'),key);if(job.provider!=='worldlabs'||!/^[a-zA-Z0-9_-]{1,180}$/.test(job.operation_id||''))throw new StudioError('Invalid world job.',403);const d=await requestProvider('operations/'+job.operation_id,key);if(d.error)throw new StudioError(d.error.message||'World generation failed.',422);if(!d.done)return reply({status:'IN_PROGRESS'});let world=d.response;if(!world?.assets&&world?.world_id)world=await requestProvider('worlds/'+encodeURIComponent(world.world_id),key);const media=[],add=(url,type,name)=>{if(typeof url==='string'&&url.startsWith('https://'))media.push({url,type,name});};const splats=world?.assets?.splats?.spz_urls||{};add(splats['500k']||splats['100k']||splats.full_res,'world','Marble-World.spz');add(world?.assets?.mesh?.collider_mesh_url,'model','Marble-Collider.glb');add(world?.assets?.imagery?.panorama_url,'image','Marble-Panorama.png');if(!media.length)throw new StudioError('World finished without supported export files.',502);return reply({status:'COMPLETED',media,worldId:world.id||world.world_id,caption:world.world_prompt?.text_prompt,cost:d.cost});
 }catch(e){return reply({error:e instanceof StudioError?e.message:'World generation service is unavailable. Check this job again.'},e.status||502);}}
export const GET=req=>handle(req,'GET');
export const POST=req=>handle(req,'POST');
